### ISSUE TITLE
Spektrum Analizer Producing Wrong Results

### ISSUE THREAD

**Issue by spatzengr** [betaflight/blackbox-log-viewer#103]
see https://www.rcgroups.com/forums/showpost.php?p=39190505&postcount=53831

the recent commit has some unintended consequences.  https://github.com/betaflight/blackbox-log-viewer/commit/9da966f3334f63db3da08161f47ef61631a4b0ec

@basdelfos

**Comment by spatzengr** [comment]
CF BBE 2.5.11:  Expected peak motor noise in 200hz range.
![image](https://user-images.githubusercontent.com/25570978/36348152-45696552-1437-11e8-8ed7-83d449432e48.png)

BF BBE 3.0.0-RC1: Committee merged resulted in peak motor noise being doubled.
![image](https://user-images.githubusercontent.com/25570978/36348157-67520b24-1437-11e8-8503-3042b074e17f.png)

**Comment by basdelfos** [comment]
Fixed with #106
