### ISSUE TITLE
[Feature Request] Set BB Log Viewer as a default application for .BFL files.

### ISSUE THREAD

**Issue by richard-scott** [betaflight/blackbox-log-viewer#109]
In Windows you can associate a .BFL file with the relevant application to open the file. It would be handy if you could do this for log files. This way we could double click on a BFL file to open it or pin logs to the Task Bar icon and access them that way.

**Comment by wolkesson** [comment]
Will need: 
1) Handling of cmd line arguments (https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments)
2) Installer to associate format

Both should be possible!
