### ISSUE TITLE
Current is recorded as centi-Amps, but displayed as Amps

### ISSUE THREAD

**Issue by basdelfos** [betaflight/blackbox-log-viewer#113]
As per PM from jflyper.

**Comment by jflyper** [comment]
I'm not sure about this anymore. Older logs that I have shows reasonable numbers displayed.
Do you have any comment? @brucesdad13

**Comment by McGiverGim** [comment]
Can you test the master of cleanflight blackbox? I think it was solved here: https://github.com/cleanflight/blackbox-log-viewer/pull/61

I've maintained more or less the cleanflight blackbox app in the latest months, so maybe is better to do a comparison between both codes to see how many changes are in cleanflight and not in betaflight. Now the code is more or less the same, only changes are branding and some fixes, for example the header page is a lot more accurate.

**Comment by basdelfos** [comment]
I just did a test with a recent recorded bb log (BF 3.3-RCx) and newest blackbox explorer. Values of amperageLatest do not have an issue. 8-10A on a hover test flight seems to be ok to me.
