### ISSUE TITLE
Probably bad frequency meassuring

### ISSUE THREAD

**Issue by apoc** [betaflight/blackbox-log-viewer#116]
There is difference between spectrum analysis and direct measurement by M key, see attached screen shot. In spectrum analysis the motor noise is about 500Hz but if I meassure directly on D-term I get the half (cca 209Hz)

![image](https://user-images.githubusercontent.com/28888/37245061-f38f82b8-2492-11e8-83fe-01c365bebdc6.png)

Gyro 32k
PID 16k
Logging 4k

**Comment by McGiverGim** [comment]
There was a bug in the firmware when Gyro loop is different from PID loop. You have more info here: https://github.com/betaflight/blackbox-log-viewer/issues/133

I close this issue. If you can, test the latest master of the firmware to verify this is solved.

**Comment by apoc** [comment]
Cool, thank You.
