### ISSUE TITLE
ESC Temperature not shown correct

### ISSUE THREAD

**Issue by pango** [betaflight/blackbox-log-viewer#118]
analog to ESC RPMs the Temperature value is not shown correctly. 
In a test flight the values were starting at 102°C and ending at 4635°C !!! Thats quite hot ;)
![bblog_temp](https://user-images.githubusercontent.com/148268/37347095-5abdaa06-26d1-11e8-87a1-20162c04ab06.jpg)

**Comment by basdelfos** [comment]
@pango I know it is a late reaction, but do you have the BB log by any chance? Could you upload it, so I can use it to solve the issue?

**Comment by basdelfos** [comment]
Nevermind, you already uploaded the BB log in issue #117.
Both issues are related btw, see #117 for further comment.

**Comment by pango** [comment]
:)
