### ISSUE TITLE
How open or cut large 16MB LOG file?

### ISSUE THREAD

**Issue by kszere** [betaflight/blackbox-log-viewer#120]
I using FC `KAKUTE V2`. Flash size for LOG data is 16MB. When I try opening this file, Chrome Crasching or MSG BOX `Page Unresponsive`.

How cut this file for few smallest?

**Comment by trendab** [comment]
Same issue here, same flight controller. Can only open really small log files.

**Comment by mikeller** [comment]
More of a firmware problem than a log viewer problem. Can you please close and open in https://github.com/betaflight/betaflight/issues?

**Comment by McGiverGim** [comment]
@kszere I've published a test version for this problem in this issue: https://github.com/betaflight/betaflight/issues/5625

**Comment by McGiverGim** [comment]
Solved in https://github.com/betaflight/betaflight/pull/5645

I think that this can be closed.
