### ISSUE TITLE
last build shows wrong sample rate

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/blackbox-log-viewer#121]
@basdelfos since #115 the viewer shows wrong sample rate and choppy lines
analyzer display shows also wrong sample rate ... and since some time the feature `FAILSAFE` in the status bar is displayed incorrectly (see screenshots)... pls can you check this

latest build with #115 
![new_build](https://user-images.githubusercontent.com/29702171/37702744-ce104c0c-2cf3-11e8-9eae-6f0ae0d94fd9.jpg)

build before #115 
![old_build](https://user-images.githubusercontent.com/29702171/37702766-dcdd6daa-2cf3-11e8-9fcc-cc007e6db5fb.jpg)

**Comment by basdelfos** [comment]
Strange, didn't notice that while testing #115, but I'm not sure I really have looked at this.
Can you send the BB log you where using while creating these screenshots?

**Comment by TheIsotopes** [comment]
BB log is on the way 

[BTFL_BLACKBOX_LOG_Mark1_20180321_100624.TXT](https://github.com/betaflight/blackbox-log-viewer/files/1836788/BTFL_BLACKBOX_LOG_Mark1_20180321_100624.TXT)
