### ISSUE TITLE
latest build #33 not working on win 10

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/blackbox-log-viewer#130]
@mikeller @McGiverGim pls can anyone check  what's wrong

when i start latest` build #33` on windows 10 i will become this failure:

![zwischenablagebild](https://user-images.githubusercontent.com/29702171/38504853-1d588f0a-3c16-11e8-98e8-908159262faf.jpg)

The procedure entry point `avcodec_receive_frame` was not found in `nw.dll`

**Comment by AndersHoglund** [comment]
Verified, I see the same problem when running the installer.

**Comment by McGiverGim** [comment]
Fixed here https://github.com/betaflight/blackbox-log-viewer/pull/131
