### ISSUE TITLE
Log Viewer v3.0.0 shows a 330hz notch at 660hz

### ISSUE THREAD

**Issue by smasslich** [betaflight/blackbox-log-viewer#133]
D-Term notch filter set at 330hz is showing in log viewer at 660hz.  This is using v3.0.0.  

Screenshot of the issue:
![notch set at 330 shows as 660](https://user-images.githubusercontent.com/38341366/38717687-039d5204-3eae-11e8-9924-51e69f14adbf.jpg)

Log File:
https://www.dropbox.com/s/3vhej8lwsf92gaw/LOG00007.BFL?dl=0

dump file:
https://www.dropbox.com/s/2jt7npkgbkksps3/BTFL_cli_X5_Silky_20180413_000729.txt?dl=0

Thanks!
Steve

**Comment by McGiverGim** [comment]
Good catch. I've found the problem/s, but I don't know which solution is best. Is a problem of the firmware, but maybe is better to fix it in the blackbox and the configurator.

**Comment by flint723** [comment]
I thought it was a configurator issue at the heart of it (not setting logging rate correctly when gyro/pid rate is unsynced) but I agree the BB Explorer should be fixed to read these type of logs correctly.  Older versions of Explorer work.

**Comment by McGiverGim** [comment]
This was solved in the firmware https://github.com/betaflight/betaflight/pull/5688 so I close this.
