### ISSUE TITLE
Default expo and zoom should be 100% for all traces

### ISSUE THREAD

**Issue by ctzsnooze** [betaflight/blackbox-log-viewer#139]
For a long time the defaults have had expo applied in varying amounts to different traces.  And some time back, not sure if it still is so, the default zoom for some traces was not 100%.

Could I please make the strong case for setting expo to zero, by default?

For example, there is no expo to motors, yet there is expo on gyro, and there is expo on RC input.  Immediately the translation between one and the other is difficult to interpret.  And if the expo on PID elements differs from one part to the next, the interpretation of how they contribute to PID sum is difficult to interpret.

I probably analyse more logs than anyone and my defaults for a long time are all expo off.  This makes it much easier to assess noise etc.  For instance with a lot of expo on a PID trace, the relative amount of noise that appears on the D trace appears to vary depending on the absolute value of D.  With expo removed, the noise is displayed properly.

I very much doubt that anyone inexperienced in blackbox would find it disturbing if the defaults were expo off on all channels.  And experienced users would probably appreciate the change in a positive way.  It would save me a lot of time.

Finally if this went ahead, pressing the 'x' key could then toggle the application of *the same amount of expo* to all relevant channels (e.g., the same expo to RC and gyro, and the same expo to all PID traces, etc).  The display would be blank normally and show 'expo' if toggled on.  I bet no-one would toggle it on.

**Comment by Aileron8** [comment]
Great idea. The first thing I do is align my expos, smoothing, and zoom if I’ve changed them or configured a new trace. This will save time and potential misguidance.
