### ISSUE TITLE
Drag and Drop files to LogViewer window / open button does not work anymore

### ISSUE THREAD

**Issue by tomidland** [betaflight/blackbox-log-viewer#143]
In 3.0.0. RC3 (and earlier I believe) it was possible to drag and drop log files to the Explorer window / Open button. That is not possible with the latest 3.0.0 as far as I can see. Can we please get this back? :)

(Tested on windows 10 x64)

**Comment by McGiverGim** [comment]
I don't remember that this was a feature of Betaflight never... are you sure that drag and drop worked?

**Comment by tomidland** [comment]
Absolutely certain!
One dragged the file to the "Open" button :)

**Comment by tomidland** [comment]
Never mind, it works now! Maybe it was my computer that had a problem! :)
