### ISSUE TITLE
UI setings affects Spectrum analyzer

### ISSUE THREAD

**Issue by Legista** [betaflight/blackbox-log-viewer#148]
When i changing Zoom in Graph setup the peaks in Analyzer changing too. 
I.e., i set 100% zoom - then i have small, normal peaks, when i set 1000% - i have so large peaks that i can't zoom down by vertical slider.
I have this settings on my gyro graph - Smooth 0, Expo 100, Zoom 1000% because i want to see noise RAW. So because of this i need to make another graph with zoom 100 to get normal spectrum data.
If that have been done intentionally you can close the issue. I just thought that no one GUI setting should affect Analyzer data.
![out1](https://user-images.githubusercontent.com/38704169/39211930-d059776c-4815-11e8-8f80-76b6e7821f46.jpg)
![out2](https://user-images.githubusercontent.com/38704169/39211937-d4770fa8-4815-11e8-86e6-efaf6828fe3b.jpg)

**Comment by ctzsnooze** [comment]
This is intended behaviour, and useful.  It allows you to vary the vertical scale of the spectrum.

Also note that the amount of flight time included in the spectrum affects how tall the spectrum will be.  Use i and o keys to select the amount of flight time that is the same, when making comparisons.

**Comment by Legista** [comment]
Thanks for reply.
I understand - it's  intended behaviour.
So this issue can be closed :)
