### ISSUE TITLE
BB explorer spectrum analyzer scale reading double

### ISSUE THREAD

**Issue by flint723** [betaflight/blackbox-log-viewer#160]
Just flashed CI build 796 (from CI build 719, before the BB fixes), and now (again) the scale in spectrum analyzer reads double what it should.  It's been fine on other new logs with synced gyro.

I know from previous logs the big spike appearing at 625hz is at ~300hz.  The visual data is correct (and it is a 4khz log based on file size), just the scale shown on the spectrum analyzer is wrong.  Not sure what is at fault here.  Sample rate appears correctly in the Explorer (1/4 for 16khz pid, 4khz log rate).  I am using 32k gyro, 16k pid, Proshot 32k.

First tried with some version of 3.3.0 (not rc1).  I tried on newest master of BB Explorer too, same result.

Here is log:
[flight 91 1000mah.zip](https://github.com/betaflight/blackbox-log-viewer/files/1969407/flight.91.1000mah.zip)
And Diff:
[diff from flight 91.txt](https://github.com/betaflight/blackbox-log-viewer/files/1969408/diff.from.flight.91.txt)

Edit: Also tried on Omnibusf4, 8k gyro 4k pid, same result.  Sample rate is correct (1/2 for 2khz log) but spectrum analyzer scale is double what it should be.  This is CI build #766.  On 8k8k log the analyzer scale works correctly.
Log:
[flight 210 hover 8k4k.zip](https://github.com/betaflight/blackbox-log-viewer/files/1969546/flight.210.hover.8k4k.zip)

**Comment by McGiverGim** [comment]
Strange, I will try to check it... maybe we missed something.

**Comment by McGiverGim** [comment]
Fixed in https://github.com/betaflight/blackbox-log-viewer/pull/135 and merged.

**Comment by flint723** [comment]
Thanks a lot!
