### ISSUE TITLE
Change the key for zoom in/out in time to t, use z for vertical scale zoom 100% vs Set

### ISSUE THREAD

**Issue by ctzsnooze** [betaflight/blackbox-log-viewer#166]
It would be very useful to be able to toggle, using a keystroke, from the vertical zoom of the graphics from as set in Graph Setup to 100%.  

This would allow the user to, for instance, set gyro zoom in the graph setup to say 800%, and toggle this detail view on or off.

Even better, if this state could be defaulted under the saved user settings, then the default behaviour could be all zooms at 100%, the user could toggle to a zoomed view as desired, and the user could sae to open zoomed or not zoomed (like the current expo and smoothing proposals).  This would be really, really good.

The logical soft key for this would be z

Unfortunately z currently toggles the *time* zoom, so can't be used for this idea.

I would be grateful if we change the toggle for *time* zoom to 't', and for vertical scale zoom to z.

Or, alternatively, keep 'z' for time zoom, and add 'v' for vertical or 'y' for 'Y axis'.  However the suggestion above is, I think, better.

**Comment by wolkesson** [comment]
I agree on zoom meaning two different things are confusing! I would suggest to call vertical zoom "scale" or "gain" and let horizontal / timewise zoom remain as just "zoom". That way keeping 'z' as the soft key won't force the few power users that actually use it to change. 

Also, I don't think overriding vertical zoom will have the intended effect. I guess you want to press this button and everything intuitively matches up. But showing 0.02 deg/s and 1780 us in the same plot without any scaling does not make much sense. Instead, I would focus on making the default zoom settings as good as possible and let this override button instead reset the user settings back to defaults.
