### ISSUE TITLE
Welcome Screen not full seen

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#18]
Welcome Screen do not full fill the maximized and reduced windows ... Scrollbar hangs in the air ;-)

maximized window:
![fullscreen_welcome-50](https://cloud.githubusercontent.com/assets/20139767/17660172/db9f6d90-62d7-11e6-89d5-2831538933c2.png)

reduced window:
![minimized_welcome-50](https://cloud.githubusercontent.com/assets/20139767/17660186/ee4729a6-62d7-11e6-827c-d79269c5b00b.png)

**Comment by GaryKeeble** [comment]
Will look into this; there seems to be some interaction with the screen size when the Viewer is run as an app from the chrome store; I think this is also related to issue #19 too.

**Comment by TheAngularity** [comment]
@GaryKeeble 

yep i'm using the viewer as an app

wow, just tested ... you're right .... open the index.html and all ok

**Comment by TheAngularity** [comment]
much better now ... thx
