### ISSUE TITLE
Gyro and Debug Misaligned

### ISSUE THREAD

**Issue by spatzengr** [betaflight/blackbox-log-viewer#185]
In the master, as of 5/23 it appears the scaling of the gyro vs. debug modes is off.  See below images from 5/11 master vs. 5/23 master.

![image](https://user-images.githubusercontent.com/25570978/40458951-c28017d6-5ecc-11e8-9165-5bc1a88eb902.png)

![image](https://user-images.githubusercontent.com/25570978/40458964-c8fc00c0-5ecc-11e8-9ed6-e063e0d208e7.png)

**Comment by McGiverGim** [comment]
Can you attach our blackbox file? Thanks!

**Comment by spatzengr** [comment]
Yes, I should have done that.  Apologies.

[2018.05.18-BF 3.4.0-Build 793_PT1=90+DyN+PT1=300_Dt=PT1-100,200-FIRST LOS.txt](https://github.com/betaflight/blackbox-log-viewer/files/2035448/2018.05.18-BF.3.4.0-Build.793_PT1.90.DyN.PT1.300_Dt.PT1-100.200-FIRST.LOS.txt)

**Comment by McGiverGim** [comment]
Tested and works with the https://github.com/betaflight/blackbox-log-viewer/pull/186
