### ISSUE TITLE
Tooltips and two srollbars

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#20]
A few Tooltips are obscured from Navigations bar, these are
* View/hide analyser display
* Zoom Analyser Window
* Jump to end of log

and also always appears two scrollbars ... imho could be related with pr #19 

![tooltip_scrollbar-50](https://cloud.githubusercontent.com/assets/20139767/17662663/746add16-62e7-11e6-8389-f5398cfcbfc5.png)
0

**Comment by GaryKeeble** [comment]
Think you are right; oddly it only happens when runnings as a chrome app...

**Comment by TheAngularity** [comment]
yep ... with open the index.html all is good but only the obscured tooltips appears
