### ISSUE TITLE
Resizing window to minimum causes program to 'crash'

### ISSUE THREAD

**Issue by Lord-Quake** [betaflight/blackbox-log-viewer#200]
Window closed to min:
![crash_small_window](https://user-images.githubusercontent.com/29223282/41029937-63fbdc66-697d-11e8-9f31-b812b48424c9.png)

Window resized. Program no longer running correctly:
![crash_window](https://user-images.githubusercontent.com/29223282/41029968-795ded1a-697d-11e8-9efe-e0aab2b4f9f2.png)

Tested on build 75

**Comment by McGiverGim** [comment]
Good catch!! ;)
