### ISSUE TITLE
Time stamp is positioned randomly near legend.

### ISSUE THREAD

**Issue by Lord-Quake** [betaflight/blackbox-log-viewer#201]
E.g. can occur when window is resized to full screen (full screen button).

See example screen shots.
![time_shift](https://user-images.githubusercontent.com/29223282/41032596-2fa5362c-6984-11e8-9a01-d9a49759a142.png)
![time_shift_1](https://user-images.githubusercontent.com/29223282/41032597-309ab2b4-6984-11e8-813f-4c7be70d814f.png)
![time_shift_2](https://user-images.githubusercontent.com/29223282/41032598-31c510a8-6984-11e8-90d0-f36e4bfff4f2.png)
![time_shift_3](https://user-images.githubusercontent.com/29223282/41032762-ac0208f8-6984-11e8-96fb-2160a0f4906e.png)

Tested on latest builds.

**Comment by Lord-Quake** [comment]
OK, I can now replicate the positioning error.
(I open the program by double clicking on a log file)

- Open the program and set it to full screen.
- Close the program. 
- Open the program once again -> The time stamp is positioned correctly.
- Resize the program to e.g. half screen size -> The time stamp is positioned incorrectly.
- Close the program.
- Reopen the program -> The time stamp is positioned correctly.
- Set program to full screen -> The time stamp is positioned incorrectly.

I'm sure the involved programmer can now find the culprit and fix the issue.

**Comment by McGiverGim** [comment]
Thanks! It was easier than that:
- Open the program
- Make it half size
- Open a log
- Maximize

Now it is fixed ;)

**Comment by Lord-Quake** [comment]
Yes, I know but you devs always are picky and want lots of details ;-)
