### ISSUE TITLE
cant open bfl's from btf 3.4 

### ISSUE THREAD

**Issue by binlan** [betaflight/blackbox-log-viewer#214]
i am recording to sd card with 500 Hz on my omnibusf4sd. the result i cant open with the latest master of blackbox-viewer. error message is just:
Error opening log: No logs in this file could be parsed successfully
i attached some logs from today.

[bfl.zip](https://github.com/betaflight/blackbox-log-viewer/files/2153028/bfl.zip)

**Comment by McGiverGim** [comment]
The log files are corrupt. This does not seem a blackbox problem. Something is wrong with your sdcard or with the firmware.

**Comment by binlan** [comment]
tried another smaller sd-card (4GB) and it works. the former 8GB is still working fine on my pc. maybe i will use it in the goggles.
i will close this issue. thx.
