### ISSUE TITLE
Cannot see everything on low resolution display.

### ISSUE THREAD

**Issue by grizewald** [betaflight/blackbox-log-viewer#227]
A small problem, but a problem none the less.

I use a small laptop with a 12" screen for my multirotor stuff. The screen resolution is only 1366x768 and the Welcome page overflows the screen without presenting a scroll bar to see vaguely important things like the version of the Black box Explorer. (This is the very latest 3.1.0 version which I installed earlier today from the amd64.deb stand-alone package. I'm running Linux Mint 18.3)

Here's what I see:

![smallscreen](https://user-images.githubusercontent.com/19938983/42460397-0b28c29e-839e-11e8-991c-8c13e33cd254.png)

Any chance of a scroll bar for the resolution challenged?

**Comment by McGiverGim** [comment]
Fixed, thanks for let us know ;)

**Comment by grizewald** [comment]
Lovely!
I tested the fix on a local installation and it works just fine. Many thanks!
