### ISSUE TITLE
better place for analyser zoom slider

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#23]
can you make the zoom sliders in relativ position to the analyser screen and not to the log graph
it looks much better ;-)

so i imagine this (only quick&dirty design):
![analyserzoom-50](https://cloud.githubusercontent.com/assets/20139767/17670094/a2f739f8-6310-11e6-9004-805a7cb62bda.png)

**Comment by GaryKeeble** [comment]
This will be in the next release.

**Comment by TheAngularity** [comment]
so i had imagined ... thx ;)
