### ISSUE TITLE
Analyser not working for a BB logs from BF 3.5RC2

### ISSUE THREAD

**Issue by supiiik** [betaflight/blackbox-log-viewer#245]
Hi,
analyser is not working in 3.2.0 for a data from BF 3.5RC2. Data from version BF3.4 are working properly.
I can see only blank analyser window there
![bb_analyzer](https://user-images.githubusercontent.com/12251616/44000149-0624c350-9e1b-11e8-8588-37dfdac804a2.JPG)

**Comment by mikeller** [comment]
Testing with a 3.5.0-RC2 log file on Blackbox Log Viewer 3.2.0, works fine for me. Can you please post a log file that does not work?

**Comment by supiiik** [comment]
[LOG00022.ZIP](https://github.com/betaflight/blackbox-log-viewer/files/2280836/LOG00022.ZIP)

**Comment by mikeller** [comment]
@supiiik: Your log has got some missing frames, and one of them is triggering a bug when trying to open the analyser. It is fixed in #246. If you let me know what platform you are on I can build you a version to test.

**Comment by supiiik** [comment]
I'm on Windows. Thanks

**Comment by mikeller** [comment]
Here you go:
https://drive.google.com/file/d/1OAi5FE3JBXQA5qiUYyZUAc9YbqKr81AQ/view?usp=sharing

**Comment by supiiik** [comment]
It's working now. Thanks :D
