### ISSUE TITLE
3.2 MacOS binary broken

### ISSUE THREAD

**Issue by ljfh001** [betaflight/blackbox-log-viewer#247]
Please see attached:
![image](https://user-images.githubusercontent.com/378514/44005880-540c914c-9e2f-11e8-80f4-386781702bf0.png)

**Comment by etracer65** [comment]
Can you provide more details like your OS version?

I just tested with OS X versions 10.10, 10.12 and 10.13 and all worked just fine.  Possibly just download it again or maybe use Safari to download instead.

**Comment by ljfh001** [comment]
10.13.6. Tried downloading it again. Still the same error.
It works perfectly fine when I launch from CMD:
/Applications/Betaflight\ Blackbox\ Explorer.app/Contents/MacOS/nwjs

**Comment by ljfh001** [comment]
sudo spctl --master-disable worked
I could do option right click to open it before. weird...

**Comment by yorb** [comment]
Same issue here, macOS 10.13.6. Tried with Chrome 68.0.3440.106 (current) and Safari 11.1.2 (13605.3.8) (also current).

This is definitely a new issue with 3.2.0, never seen it before. Let me know how else I can help troubleshoot!
