### ISSUE TITLE
hidden stick display reappears

### ISSUE THREAD

**Issue by ghost** [betaflight/blackbox-log-viewer#25]
hidden stick display reappears when you press shortcut "S", "X" or "G" ... :(

**Comment by TheAngularity** [comment]
@GaryKeeble ... have you a solution

**Comment by GaryKeeble** [comment]
No solution yet; this will be part of the cleanup of the User Settings mechanism that I am hoping to release as part of the v2.5.4 cleanup.

**Comment by wolkesson** [comment]
This is still a bug!!! I've not reached the core why options.drawSticks are not retained when for example "QuickSmooth" is used. But for some reason, the sticks are drawn in the same canvas as the graphs, but the craft and analyzer are drawn in separate ones. The separate canvases are hidden/shown with CSS styles. While the sticks are hidden with a flag in grapher.js. Is there a reason for this inconsistent or would you like me to create a PR with the sticks as a separate canvas, hidden and shown as the others? Would also be nice to split the code into separate files and building components down the line.

**Comment by McGiverGim** [comment]
@wolkesson any cleaning in the code is always welcome. If you can do the PR it will be great!

**Comment by wolkesson** [comment]
I'm working on a PR for this! Will split out the sticks to separate canvas and a separate js-file. I'll take a couple of days more.
