### ISSUE TITLE
Application hangs when opening BT 3.5.0 logs

### ISSUE THREAD

**Issue by jorgecam** [betaflight/blackbox-log-viewer#253]
Hi,

the application hangs when trying to open logs registered with BT 3.5.0 on a SP F3 board.

Here is an example log to check if somebody can open it. 

Thanks !!!!
Jorge
[BTFL_BLACKBOX_LOG_20180910_233219.zip](https://github.com/betaflight/blackbox-log-viewer/files/2375550/BTFL_BLACKBOX_LOG_20180910_233219.zip)

**Comment by mikeller** [comment]
@jorgecam: It looks like either your log has a malformed header, or else the configuration of your flight controller is corrupted: `frameIntervalPDenom: 0`

Can you please post a `diff` of the configuration of the flight controller that produced this log?

**Comment by jorgecam** [comment]
Thanks mikeller, this is the diff:

diff
# Betaflight / SPRACINGF3 (SRF3) 3.5.1 Sep  8 2018 / 05:52:39 (d9fb5ca13) MSP API: 1.40


feature -RX_PPM
feature -TELEMETRY
feature -RSSI_ADC
feature MOTOR_STOP
feature RX_PARALLEL_PWM
feature AIRMODE
map TAER1234
serial 2 0 57600 57600 0 115200
aux 0 0 1 1200 2100 0 0
aux 1 1 1 1200 1400 0 0
aux 2 2 1 1400 1600 0 0
set acc_calibration = 11,40,55
set mag_hardware = NONE
set baro_hardware = NONE
set min_check = 1130
set min_throttle = 1090
set use_unsynced_pwm = OFF
set motor_pwm_protocol = OFF
set motor_pwm_rate = 480
set failsafe_switch_mode = STAGE2
set failsafe_procedure = AUTO-LAND
set deadband = 3
set yaw_deadband = 5
set pid_process_denom = 5
profile 0

set dterm_notch_cutoff = 0
set p_pitch = 75
set i_pitch = 55
set d_pitch = 30
set p_roll = 75
set d_roll = 35
set p_yaw = 90
set i_yaw = 60
set f_yaw = 0
set p_level = 25
set i_level = 25
rateprofile 0

set yaw_rc_rate = 130

#

**Comment by jorgecam** [comment]
Hi, problem solved. 

In the Betaflight configurator Blackbox window, I leaved blank the "blackbox logging rate", and then save and reboot. Selecting 500 Hz everything works great.

thanks !!!!!
