### ISSUE TITLE
3.2 BBLV stop working. No analyzer window.

### ISSUE THREAD

**Issue by mixMugz** [betaflight/blackbox-log-viewer#254]
File open in BBLV, playin' 10 second, then stop working.

There is BB file from BF 3.5.0
https://www.dropbox.com/s/gsprk3j11ycysr3/BTFL_BLACKBOX_LOG_ncu%5Bx%5D_20180917_213451.BBL.zip?dl=0

**Comment by McGiverGim** [comment]
The fix was included some time ago, so I close this issue.
