### ISSUE TITLE
overlapped log graph

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#26]
i'm used the viewer as an chrome app in maximised window ... on first open a new logfile the log graph display is overlapped from the control panel ... but this does not always

![fullsreen-50](https://cloud.githubusercontent.com/assets/20139767/17701349/d34e328c-63c9-11e6-8eab-6e6ef5a57794.png)

**Comment by TheAngularity** [comment]
@GaryKeeble ... here there is also no solution :(

**Comment by GaryKeeble** [comment]
I can replicate this problem; and resizing the window after the display is shown clears the issue temporarily. 
I am working on a solution at the moment as part of a cleanup of the UI code that will be part of 2.5.4

**Comment by GaryKeeble** [comment]
Just an update on this long-standing bug;

I believe (hope) the issue is now resolved in the next release v2.5.7

**Comment by TheAngularity** [comment]
yep ... well seems to be resolved now ;-)

**Comment by TheAngularity** [comment]
Ok, I guess the bug is eliminated ... closed now ;)
