### ISSUE TITLE
RC Command selection only initially shows throttle in the graph

### ISSUE THREAD

**Issue by etracer65** [betaflight/blackbox-log-viewer#27]
If you choose the preset graph "RC Command" labels for all the items appear (roll, pitch, yaw and throttle), but the graph only shows throttle.  If you change the graph settings at all then the other graphs show up.

**Comment by GaryKeeble** [comment]
I believe I have a fix for this that will be released as part of 2.5.4;

**Comment by GaryKeeble** [comment]
Fixed in 2.5.5
