### ISSUE TITLE
Uninstaller list is wrong under Windows

### ISSUE THREAD

**Issue by McGiverGim** [betaflight/blackbox-log-viewer#272]
The installer creates a file with a list with all the files to uninstall if desired. But in the blackbox the name is wrong because we forgot one define in the nsis installer:

![image](https://user-images.githubusercontent.com/2673520/51920995-ca00a180-23e6-11e9-81e6-9bcb6aff6e78.png)

I don't know if we want fix it:
- If we define the correct name, it will throw an error when installing the next version, but all will work and will be corrected since then.
- We can add an IF to the installer to detect which version we are, but is code to maintain.

**Comment by mikeller** [comment]
Good find!

I think fixing this would be nice - not sure how complex it will be to add the differentiation to the installer, but I'd hope that it won't require much maintenance.

**Comment by mikeller** [comment]
I haven't seen this because I am using linux. :stuck_out_tongue_winking_eye:
