### ISSUE TITLE
BlackBox log viewer v3.2.0+BF4.0RC4 wrong voltage match

### ISSUE THREAD

**Issue by watageek** [betaflight/blackbox-log-viewer#292]
![voltage blackbox](https://user-images.githubusercontent.com/25552059/55198052-da38c100-518a-11e9-8620-eef11b9f83ec.png)

![voltage 3 5 7](https://user-images.githubusercontent.com/25552059/55198313-e709e480-518b-11e9-973d-79cb5f8ee116.png)

[log.zip](https://github.com/betaflight/blackbox-log-viewer/files/3020431/log.zip)
[diff.zip](https://github.com/betaflight/blackbox-log-viewer/files/3020433/diff.zip)
[diff 3.5.7.zip](https://github.com/betaflight/blackbox-log-viewer/files/3020436/diff.3.5.7.zip)

Focus mainly on the voltage shown in the blackbox explorer.

Best regards

**Comment by mikeller** [comment]
This is due to a change in decimal places for how voltage is reported in the firmware, and the latest released blackbox log viewer not being aware of this change. Version 3.3.0 (to be released in a week or so) will fix this, or you can use the latest version built from the repository.

**Comment by watageek** [comment]
Thank you very much for the swift reply. I should have thought of it.👌
