### ISSUE TITLE
Static Craft Display when disable accelerometer (Acro Mode - Active)

### ISSUE THREAD

**Issue by abimaputra78** [betaflight/blackbox-log-viewer#294]
Dear BF BB Team,

after activate the Acro mode and disable the accelerometer on my quad, i had my craft display was "static" when i was doing roll and flips.  this might be different when acro + accelerometer activated, the craft can be seen flips and rolls and crash also. would you please advice for this issue. 

thanks.
Ditto.

**Comment by abimaputra78** [comment]
![image](https://user-images.githubusercontent.com/49124286/55290929-93a1cb80-5403-11e9-9013-fa3b35282559.png)

**Comment by mikeller** [comment]
@abimaputra78: This is expected behaviour - without ACC there is no way for the craft to determine its exact attitude.
