### ISSUE TITLE
Gyro graphs are out of range

### ISSUE THREAD

**Issue by guillermo3r** [betaflight/blackbox-log-viewer#307]
Look at this log
![Anotación 2019-04-15 185640](https://user-images.githubusercontent.com/351059/56150961-6717b300-5fb0-11e9-97e6-a6125e44672d.jpg)

All graphs are out of range in BBL 3.3.0

**Comment by McGiverGim** [comment]
I have no problems with it. Can you attach your log?

**Comment by guillermo3r** [comment]
Sure
[BTFL_BLACKBOX_LOG_FeNix_20180724_142850.log](https://github.com/betaflight/blackbox-log-viewer/files/3081363/BTFL_BLACKBOX_LOG_FeNix_20180724_142850.log)

**Comment by guillermo3r** [comment]
Sorry I closed the issue by mistake

**Comment by McGiverGim** [comment]
I will look into it tomorrow, now I'm out of the computer 😉
