### ISSUE TITLE
Blackbox log viewer 3.3.0 - Log files with firmware betaflight 3.5.x are displaying strange related gyro datas graphs

### ISSUE THREAD

**Issue by blackmennewstyle** [betaflight/blackbox-log-viewer#310]
Is it normal when i try to open log files on firmware 3.5.x with the Betaflight Blackbox Viewer 3.3.0 that i get strange graphs for most gyro datas?

- Log file with firmware Betaflight 3.5.5
![blackbox_viewer_3 3 0_betaflight_firmware_3 5 5](https://user-images.githubusercontent.com/4682874/56480757-b3e61700-64e5-11e9-8318-1c6dee11ed1b.jpg)

- Log file with firmware Betaflight 3.5.7
![blackbox_viewer_3 3 0_betaflight_firmware_3 5 7](https://user-images.githubusercontent.com/4682874/56480758-b3e61700-64e5-11e9-8db6-241ea0f2c99d.jpg)

Do i have to run the dedicated blackbox viewer for each different version of betaflight firmware i am using on my panel of quads? :'(

**Comment by McGiverGim** [comment]
This has been fixed in master: https://github.com/betaflight/blackbox-log-viewer/pull/308 until a new release, you can build yourself a version or go to your installed 3.3.0 directory, all the files are there in plain text, and make the same change of the PR.

**Comment by blackmennewstyle** [comment]
> 
> 
> This has been fixed in master: #308 until a new release, you can build yourself a version or go to your installed 3.3.0 directory, all the files are there in plain text, and make the same change of the PR.
> 
> EDIT: Sorry, only the Configurator is in plain text, Blackbox are compressed.

Thank you so much for the answer :)

No worry i installed the 3.2.0 blackbox viewer in a virtual machine so i can deal with both. I won't be using them both for a long time anyway, currently moving everything to Betaflight 4.0.0 <3

Have a great week and keep on flying!

**Comment by McGiverGim** [comment]
@blackmennewstyle a new release 3.3.1 has been published that must fix it. Can you test it please?

**Comment by blackmennewstyle** [comment]
> 
> 
> @blackmennewstyle a new release 3.3.1 has been published that must fix it. Can you test it please?

Hi :)

Thanks for the heads-up. I just tested it out and everything look to be fixed and working properly :D

- Log file with firmware Betaflight 3.5.5
![blackbox_2](https://user-images.githubusercontent.com/4682874/56899236-285c1f80-6abd-11e9-8606-9654d52e49d6.jpg)

- Log file with firmware Betaflight 3.5.7
![blackbox_1](https://user-images.githubusercontent.com/4682874/56899409-90126a80-6abd-11e9-8a45-4bf517371670.jpg)

Have a great week :)

**Comment by mikeller** [comment]
@blackmennewstyle: In this case can you close the issue please?

**Comment by blackmennewstyle** [comment]
> 
> 
> @blackmennewstyle: In this case can you close the issue please?

Oh sorry. Done :)
