### ISSUE TITLE
Cannot download Windows Release 3.3.1.EXE

### ISSUE THREAD

**Issue by watageek** [betaflight/blackbox-log-viewer#319]
![3 3 1](https://user-images.githubusercontent.com/25552059/56913665-3ccdf700-6a80-11e9-8182-13de0e639016.png)
every link works except
 win.exe

**Comment by mikeller** [comment]
@watageek: Looks like GitHub / AWS had a temporary issue. I just downloaded / executed the 3.3.1 Windows installer successfully

**Comment by watageek** [comment]
Yes. 
Thank you for the swift answer.
