### ISSUE TITLE
When plotting RSSI, no numeric value is displayed

### ISSUE THREAD

**Issue by dabit20** [betaflight/blackbox-log-viewer#325]
When I plot RSSI, no numeric value is displayed.

BB Log explorer: 3.3.1
BF version: 4.1 (JoeLucid inverted DShot test)

[2btfl_001.zip](https://github.com/betaflight/blackbox-log-viewer/files/3144092/2btfl_001.zip)
![image](https://user-images.githubusercontent.com/24653037/57175361-52119f80-6e4b-11e9-9ac3-42f680d5ab0a.png)

**Comment by McGiverGim** [comment]
I will look into it, thanks!
