### ISSUE TITLE
BB Log to GoPro video auto-sync

### ISSUE THREAD

**Issue by bizmar** [betaflight/blackbox-log-viewer#339]
_This is an idea that should work, and feel like magic. Syncing video in BB viewer is not common enough to justify development time. I'm putting it here because I think it's neat. May be a good student project, if you are really ambitious, and want a challenging Fourier Transfer based project._ 

GoPro cameras embed onboard gyro data into MP4s
~400 Hz 3-axis gyro readings
~200 Hz 3-axis accelerometer readings
~18 Hz GPS position (lat/lon/alt/spd)
(Sessions don't have GPS)
1 Hz GPS timestamps 
1 Hz GPS accuracy (cm) and fix (2d/3d)
1 Hz temperature of camera

https://github.com/gopro/gpmf-parser
https://github.com/stilldavid/gopro-utils

Extracted gyro data would be compared and synced.
It could also batch compare a folder of videos and logs and automatically pair them together.

Here's a project doing this with audio https://github.com/jeorgen/align-videos-by-sound

**Comment by McGiverGim** [comment]
It seems a good idea to me but I'm not able to implement it. I see it very difficult. Maybe others have enough knowledge to do it.
