### ISSUE TITLE
Betaflight Chip not found

### ISSUE THREAD

**Issue by TheFuuzer** [betaflight/blackbox-log-viewer#343]
Hi, I have a matekf405-ctr and connecting it to betaflight I see all the data (gyroscope, accelerometer etc.) but it tells me chips not found for flashing, I have a sd card inserted and I can't flash and enter settings. How do I solve it?

**Comment by McGiverGim** [comment]
You are at the wrong place. This is for software issues of the Blackbox Viewer. For user support go to rcgroups or the Betaflight Slack.
Your problem seems a problem with the dfu driver but installed, but as I say this is not the place.
Regards!
