### ISSUE TITLE
decoded values into CSV file

### ISSUE THREAD

**Issue by farmingmachine** [betaflight/blackbox-log-viewer#349]
Hey,

it would be rlly if we could also export the decoded values (e.g. pitch angle) to the CSV-file instead of only the raw data. Could that be made possible?

Kind regards,

Malik

**Comment by mikeller** [comment]
Not sure this makes sense and does not just add bloat - these can easily be calculated based on the raw data.

**Comment by farmingmachine** [comment]
Yeah you're right , I just realized that as well. Sorry for the trouble ^^

Michael Keller <notifications@github.com> schrieb am Mi., 26. Juni 2019,
23:27:

**Comment by farmingmachine** [comment]
> Not sure this makes sense and does not just add bloat - these can easily be calculated based on the raw data.

Could you tell me the factors to calculate the raw pitch and roll into angles values? Since the values are rounded in the viewer, it's kinda tricky to get the real factors

**Comment by Mahdi-Hosseinali** [comment]
Is there any reference for decoding the raw values?
I'm specifically interested in motors. Not sure what are the units of the raw data and if the decoded values are percentages of the maximum RPM, duty cycle, etc?
