### ISSUE TITLE
Possible incorrect motor ordering

### ISSUE THREAD

**Issue by filip-cz** [betaflight/blackbox-log-viewer#351]
I have a suspicion that motor ordering in _Craft display_ does not respect the Betaflight _Configuration/Mixer_ setting. 

I am currently using the Quad X 1234 setting in Betaflight but I believe that _Quad X_ settings is being used for _Craft display_ feature.

**Comment by McGiverGim** [comment]
The Blackbox log does not inform about the mixer/motor order settings. If you want to visualize it correct, I think remember that in the options menu you can select the motor ordering.
