### ISSUE TITLE
Debug_Mode=DUAL_Gyro_Raw Reversed

### ISSUE THREAD

**Issue by spatzengr** [betaflight/blackbox-log-viewer#353]
It appears like the Debug mode descriptions for Dual_Gyro_Raw are revered for Pitch vs. Roll.  It appears to me the Debug[0] and Debug[3] are roll in this case and Debug[1] and Debug[2] are pitch.

![image](https://user-images.githubusercontent.com/25570978/61092138-1549c200-a413-11e9-80d3-93710368e3a9.png)

[LOG00011.zip](https://github.com/betaflight/blackbox-log-viewer/files/3384350/LOG00011.zip)

**Comment by Docteh** [comment]
Isn't it a best practice to mount the second gyro 90 degrees different from the first?

Or is raw supposed to be after factoring that in?

**Comment by etracer65** [comment]
`RAW` data from the sensors is not translated based on mounting orientation. Roll is the gyro's X axis, pitch is Y axis and yaw is Z axis. So if the two gyros are mounted with a 90 degree offset then it will result in the data you're seeing.

Anyway you'd probably be better off using the `DUAL_GYRO_SCALED` debug mode as that has the roll/pitch values scaled to degrees/sec and aligned based on the sensor orientation.
