### ISSUE TITLE
compatible with bf3.1.0 log file

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#36]
is the log viewer compatible with bf3.1.0 log files? i can't no more see the notch margins.
here is a screenshot (see top left) and the log file:
![zwischenablagebild](https://cloud.githubusercontent.com/assets/20139767/19731731/b3261972-9b9e-11e6-86b0-ae5398a91a84.jpg)

[LOG00002.TXT](https://github.com/betaflight/blackbox-log-viewer/files/553664/LOG00002.TXT)

with the old bf3.0.1 i have no probs to see the notch margins.

**Comment by borisbstyle** [comment]
3.1 is not released yet. Still developed

**Comment by GaryKeeble** [comment]
Yes, I can confirm this as a bug in the viewer; have fixed it in the latest commit to version 2.5.8.
