### ISSUE TITLE
Feature request - display keyboard preset number for graph display

### ISSUE THREAD

**Issue by ian444** [betaflight/blackbox-log-viewer#360]
Feature request - I would like to see what keyboard preset (1-9) I have currently selected beside the word "Legend" at the top RHS. Could this be implemented (if it's considered a worthwhile idea)? I often find myself wondering which preset I'm on and how to get back to it without cycling through all the numbers.

**Comment by ian444** [comment]
Feature request - I would like to see what keyboard preset (1-9) I have currently selected beside the word "Legend" at the top RHS. Could this be implemented (if it's considered a worthwhile idea)? I often find myself wondering which preset I'm on and how to get back to it without cycling through all the numbers.

**Comment by wolkesson** [comment]
I would say this is fixed by #390 since the current "keyboard preset number" (now "workspace number") is shown on the dropdown. I admit it's not on the legend, but close enough.

**Comment by McGiverGim** [comment]
I close this then. Thanks @wolkesson !!
