### ISSUE TITLE
Release Blackbox Parser as NPM Module

### ISSUE THREAD

**Issue by Swinkid** [betaflight/blackbox-log-viewer#363]
Hey,

Is their any plans to release just the javascript blackbox parser as a NPM Module? If not, are others allowed to? Wanted to implement my own parser, but the BFL files arn't easy to understand and little documentation to decode!

Thanks!

**Comment by mikeller** [comment]
@Swinkid: There were no plans - until right now it appears. ;-)

I think this would be a great opportunity to make the parsing (and with it the awareness of differences in past and future versions) available for other developers and projects.
Happy to help with this, and I think it's probably best to keep this npm module inside the Betaflight project, to facilitate coordination of changes to the log file format.

**Comment by Swinkid** [comment]
Any ideas on where to start and suggest project structure? Obviously want to set it up in a way that the whole project isn't published to NPM. Also might be worth trying out the new packages feature in github too.

Cheers!

**Comment by mikeller** [comment]
I'd probably cut as low down as possible - create a library that can read data out of a log file, and return it as data structures.

**Comment by Docteh** [comment]
@Swinkid Hacktoberfest!

**Comment by Swinkid** [comment]
It's coming, i just had to finish my master's thesis. Now. Free!

**Comment by Docteh** [comment]
I actually haven't given the blackbox viewer much consideration, based on file names I'd start with `js/flightlog_*`
