### ISSUE TITLE
Export worskpaces does not work

### ISSUE THREAD

**Issue by eried** [betaflight/blackbox-log-viewer#364]
I get an empty looking configuration:
![image](https://user-images.githubusercontent.com/1091420/64513088-1484bd80-d2e8-11e9-8fdb-6aaab0aa3ea0.png)

Windows 10 x64, version 3.3.1

**Comment by McGiverGim** [comment]
You must save before in a number, with shift+number. The save workspaces only save the stored ones.

**Comment by eried** [comment]
Oh, I see, thanks!
