### ISSUE TITLE
Selecting sub logs doesn't move the video timelime

### ISSUE THREAD

**Issue by pierreh** [betaflight/blackbox-log-viewer#367]
If I load a complete video of a flight and the flight has three sublogs due to landing, disarm, arm and fly again. Then when I select a sublog the video doesn't scroll to the correct timestamp and I have to offset the log everytime I select a different sublog.

**Comment by etracer65** [comment]
The three logs are independent and not related. There's no way to know that they're part of the same video. Also we have no way of knowing the time interval between each log.

**Comment by rinchen-clubhouse** [comment]
The log header have a `Log start datetime` which can be used to locate the position on the timeline, relative to the first header.

**Comment by pierreh** [comment]
The log header have a Log start datetime which can be used to locate the position on the timeline, relative to the first header.

**Comment by etracer65** [comment]
Most of the time the log header timestamp will be 0. The flight controllers have no realtime clock and the time can only be set through a USB connection to the configurator, from GPS (if used and locked), or through using the Lua scripts over telemetry from the transmitter. The time is lost when the flight controller is power cycled.

**Comment by pierreh** [comment]
Ah right, I have GPS, I was wondering how it got the time :-)
Perhaps we can have a separate offset per sublog and use the duration of the previous sublog as a default to add to the offset?
like `default offset (n) = offset(n-1) + duration(n-1)`

**Comment by etracer65** [comment]
That might be a possibility for the future, but that data is currently not written to the log. But still doesn't solve the case where the video continued to roll but the quad was power cycled or reboot (like going into the OSD menus and changing settings). The time or "time index" won't survive the reboot.
