### ISSUE TITLE
Feature request - highlight active graph when you mouse-over the legend

### ISSUE THREAD

**Issue by rodgerramjet** [betaflight/blackbox-log-viewer#37]
Think most graphing programs do this... i struggle with the colours of the graphs as I'm colour blind... this sort of usability assist is useful

Example (there are tonnes out there)
http://www.highcharts.com/demo/line-basic

**Comment by GaryKeeble** [comment]
Interesting; I'll look into it

**Comment by wolkesson** [comment]
I'm also struggling with this when looking at logs outside in the sunlight. I've made some tests and will do a PR in a while.

**Comment by wolkesson** [comment]
Just, wanted to say that I'm working on this and will have a PR ready in a few days.

**Comment by rodgerramjet** [comment]
Awesome- thank you @wolkesson
