### ISSUE TITLE
Feature: Give Workspaces "titles/names" and display this name as legend title

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/blackbox-log-viewer#373]
It would be helpful, if user use different workspace favorites (like UAVTech.json). To give the user a better overview its helpful if a favorites contains a title and this title is displayed on the legend canvas.

<img width="879" alt="BBF_3 4 0_feature01" src="https://user-images.githubusercontent.com/949032/66027911-3561bc80-e4fc-11e9-8453-21666bdb1ba5.png">

**Comment by wolkesson** [comment]
I'm working on this! The goal is to also make:
- the title editable by double-click
- a dropdown for selecting workspace, same as pressing [1-9]
- A save workspace button, same a pressing shift+[1-9]
- Make it backwards compatible...

Anyone; is it better to put it on the toolbar, next to time? Possibly a workspace could be more than only a graph config. It could for example be an analyser overlay or show/hide states of stick and craft.

**Comment by wolkesson** [comment]
Hacking around a bit and decided on a more elaborate solution: 
![image](https://user-images.githubusercontent.com/5307773/66707543-47d0c700-ed42-11e9-8077-6aa894055773.png)

![image](https://user-images.githubusercontent.com/5307773/66707579-faa12500-ed42-11e9-93ac-fb723b31f617.png)

Still some work to do with backward compatibility and actually showing it in the title in the legend. Keyboard commands will be as before. 
This also solve #360 

Feedback is welcome! PR in a couple of days.

**Comment by mrRobot62** [comment]
Hi @wolkesson - sorry for this late response :-( - I think your solution with a combobox is nice and give the user the possibility to change a workspace very easy. To edit names is perfect.

Good solution (for me ;-) )

**Comment by mrRobot62** [comment]
Update: if you enabling "editing workspace name" please write it back into workspace json file, that would be comfortable for users

**Comment by wolkesson** [comment]
Have a look at the PR #390. :D 
Workspace names are written to the json. Required a new format, but it's backwards compatible, meaning you will be able to open for example UAVTech.json. However new files will not open in older versions. A good way of testing this out is to give names to all the workspaces in UAVTech according to this description: https://drive.google.com/open?id=18a-YCHqF720qgsbw7XNrANm0juFsLNPD

**Comment by mrRobot62** [comment]
ui - seems to be very comfortable :-) - will download current branch and create a dmg-file. Unfortunately not today and maybe not tomorrow :-( - If done, I will give a feedback

**Comment by mrRobot62** [comment]
I testes 3.5.0RC1 with @wolkesson extension - works fine - but I found following "unsharpness" ;-)

- Workspace name length:
if to long ... dots are shown, but no chance to see (e.g. tooltip) the complete name:
Solution: max number of chars or tooltip or wider box

<img width="186" alt="image" src="https://user-images.githubusercontent.com/949032/67404817-31cdcc80-f5b4-11e9-8232-82945209edc3.png">


-

**Comment by mrRobot62** [comment]
made a small enhancement for this feature.
<img width="674" alt="BBE_Feature_373" src="https://user-images.githubusercontent.com/949032/68086229-9fe28100-fe49-11e9-82e1-f59c9ed1d76f.png">

**Comment by mrRobot62** [comment]
done with #400/#401
