### ISSUE TITLE
maximized window is not saved

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/blackbox-log-viewer#377]
After closing the maximized window and reopening, the window is minimized again.

**Comment by mrRobot62** [comment]
On OSX BBE opens every time with full windows size (max).
Neither the windows size nor the position is saved

**Comment by TheIsotopes** [comment]
tested now with current master and now it is worse than before.

@McGiverGim pls can you fix this

![blackbox_explorer](https://user-images.githubusercontent.com/29702171/86607387-787c1f00-bfa9-11ea-99a9-d090137bd65b.jpg)

**Comment by McGiverGim** [comment]
I will look into it this week if I have some time, I don't promise ;)
