### ISSUE TITLE
Gyro Data not Readable

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/blackbox-log-viewer#38]
See 
https://github.com/betaflight/betaflight/issues/1732

@martinbudden 
Blackbox issues can be created here

**Comment by GaryKeeble** [comment]
Have modified master to check for gyro_scale as well as gyro.scale (to keep compatibility with old logs). Also, default gyro scaling to 1.0 for BF3.1.0 as scaling is now handled in the flight controller.

**Comment by TheAngularity** [comment]
tested your new master ... the logfile i posted looks like correct ... but now old 3.1,0 log files are displayed differently ... i think this is due to the changes in the betaflight code

**Comment by TheAngularity** [comment]
the one would be fixed already times ... but vbat issues is still in the room

**Comment by GaryKeeble** [comment]
@TheAngularity, Yes, the version check for the gyro scale is based on the version 3.1.0; so old 3.1.0 logs will not display correctly; only 3.1.0 logs from this point forward or logs prior to 3.1.0 will display correctly.

Still investigating vbat scaling.

**Comment by mikeller** [comment]
Could the vBat issues be related to the changeover from storing vBatLatest as raw ADC reading to storing it as voltage?

**Comment by GaryKeeble** [comment]
@mikeller, thanks, that makes a lot of sense, the logged values hover around 168..148 which is possibly 16.8v to 14.8v.... will take a look....

**Comment by martinbudden** [comment]
@GaryKeeble the betaflight PR https://github.com/betaflight/betaflight/pull/1853 now sets the scale correctly, so presumably your change to check the version number can be removed.

**Comment by GaryKeeble** [comment]
@martinbudden; OK; will revert the change :-)

**Comment by TheAngularity** [comment]
@GaryKeeble 
But still a small question ... how does it look with the vbat issues?

**Comment by GaryKeeble** [comment]
Will start investigating the vbat next :-)

**Comment by GaryKeeble** [comment]
@TheAngularity, Just pushed a fix for the VBAT scaling; works on the bench.

Happy New Year to you too :-)

**Comment by TheAngularity** [comment]
will give it a try ... here another #44

**Comment by TheAngularity** [comment]
@GaryKeeble @borisbstyle 
Looks good again now ... thx ... I think It can closed now ;-)

**Comment by wolkesson** [comment]
Close this! ;-)
