### ISSUE TITLE
No audio played in viewer 3.4.0

### ISSUE THREAD

**Issue by dischinator** [betaflight/blackbox-log-viewer#387]
Since I upgraded to viewer 3.4.0 during playback of my videos no audio is played. The same files worked fine on version 3.3

Since this might be related to the audio codec used, this is the ffprobe info for one of my files:

>  Duration: 00:05:02.05, start: 0.000000, bitrate: 8706 kb/s
>    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 8561 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
>    Metadata:
>      handler_name    : Video Handler
>    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 96000 Hz, stereo, fltp, 128 kb/s (default)
>    Metadata:
>      handler_name    : Audio Handler

**Comment by mikeller** [comment]
@dischinator: Blackbox Explorer is using the video codecs from https://github.com/iteufel/nwjs-ffmpeg-prebuilt. If the version used in Blackbox Explorer (0.31.5) does not support audio on your platform you'll have to report this as a bug against this project.
