### ISSUE TITLE
remove gradients

### ISSUE THREAD

**Issue by meoso** [betaflight/blackbox-log-viewer#406]
Is there a way to remove the graphical gradients? or can the source-code to produce them, be removed altogether?  it interferes with overlaying any exported video onto flights in other post-production software.  

[![2019-11-07-15-29.png](https://i.postimg.cc/zGBvJ6nS/2019-11-07-15-29.png)](https://postimg.cc/jLptc83L)

my 3rd party software works great to overlay exported video and see the flight footage underneath, the only downfall is i see a slight variation of color due to these gradients.

**Comment by wolkesson** [comment]
Faily easy to fix. Just don't know where to put the setting? 
![image](https://user-images.githubusercontent.com/5307773/68979235-48ef8b00-07fd-11ea-87a7-65a7f40e4bb4.png)
Or, should we remove them all together? Would anyone actually miss them? I know that it is for showing signal scale, but that's what grids are for.

**Comment by mikeller** [comment]
In a perfect world (i.e. without customers :laughing: ) I'd say remove. But since there are sure some to be sad about it being gone, we already have it, and the cost for making it switchable isn't going to be huge, I'd say keep it, make it switchable, and default to off.
If nobody complains about it being gone after this we can remove it in the next version. :wink: 
Position looks good to me.

**Comment by mikeller** [comment]
Update: On second thought, these settings could probably do with some reorganising - they are mostly single item groups now which is a bit daft.

How about:
- Craft
-- Use custom Mixer
-- Positions
- Display
-- Show units on legend
-- Show watermark
-- Show background gradient
-- Show Lap timer
(leave Stick Settings / Analyser Settings as they are)

@McGiverGim: Thoughts?

Also, this can be done in a separate pull request.

**Comment by wolkesson** [comment]
I was just going to suggest something similar. I have a pull request for this the gradient on/off feature ready. Also thinking that in Advanced Settings there are settings for show/hide lap timer and watermark, but not for show/hide of sticks and craft. These are instead controlled from the toolbar. Shouldn't we move lap timer and watermark to the toolbar too? Maybe making the overlay into a dropdown (not only for smaller screens) and putting all that has to do with visibility here?

I suggest a new issue for restructuring settings dialog.

**Comment by mikeller** [comment]
@wolkesson: Yes re adding these show / hide settings to the menu - their discoverability at the moment is horrid.

**Comment by McGiverGim** [comment]
To me is ok. I think a reorder is good.

**Comment by meoso** [comment]
i could be wrong, but this never did anything that i could see.. maybe toggle it with this icon:
![2019-11-16_15-13](https://user-images.githubusercontent.com/1337447/68999249-bf36d080-0883-11ea-9d6c-0b4bc294f988.png)

in the meantime, i just changed  `rgba(255,255,255,0.1)');` to `axisGradient.addColorStop(0.0,   'rgba(0,0,0,0)');` in `js/grapher.js` lines 413,417 and compiled.

**Comment by wolkesson** [comment]
For the grid button usage see #407 
For the fix of gradient there is a pull request #408 
🕹
