### ISSUE TITLE
Grid feature is hard to use

### ISSUE THREAD

**Issue by wolkesson** [betaflight/blackbox-log-viewer#407]
To display a grid you need to know that you should hold alt and click a field in the legend. Then you also need to turn "master grid switch" on (G key).

**Comment by mikeller** [comment]
Don't you need to poke you your tongue while you're doing it as well and pinch your nose? :stuck_out_tongue_closed_eyes:

**Comment by wolkesson** [comment]
I'll add a column with checkboxes to the Graph Setup for review for turning Grid On/Off for that field.
