### ISSUE TITLE
Feature Request - Log Header Information clean up

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/blackbox-log-viewer#42]
@GaryKeeble 

pls can you clean up the log header information to reflect bf 3.1.0 

remove betaflight pid controller 

![zwischenablagebild 1](https://cloud.githubusercontent.com/assets/20139767/21570483/bda2c08e-cec6-11e6-8854-d0ed21ab6dbd.jpg)

insert the unknown header fields and also the features osd and esc_sensor ... also remove the features oneshot125 and superexpo_rates

![zwischenablagebild](https://cloud.githubusercontent.com/assets/20139767/21570454/6d45901c-cec6-11e6-8460-39d54571177e.jpg)

**Comment by GaryKeeble** [comment]
Yes,
I'll start to sort these things out; a clean-up has been on my list for some time now :-)

**Comment by TheAngularity** [comment]
tested your latest viewer cleanup ...  looks good again 👍

**Comment by TheAngularity** [comment]
new request ... you could still move the debug settings from right to left at the bottom ... shortening the log header information output ;-)

**Comment by TheAngularity** [comment]
@GaryKeeble 

> new request ... you could still move the debug settings from right to left at the bottom ... shortening the log header information output ;-)

imho this is the last request ... then everything seems to be good ;-))

**Comment by GaryKeeble** [comment]
Swapped the Debug Settings over to the left; and moved the "unknown header fields" over to the right as this is usually hidden unless there is a conflict.

**Comment by TheAngularity** [comment]
ok ... yeep ... looks very good now ... thx 👍 

wish you a happy New Year ;-)
