### ISSUE TITLE
Add legend to the analyser display

### ISSUE THREAD

**Issue by mikeller** [betaflight/blackbox-log-viewer#423]
Currently, when the analyser display is opened, there is no indication of what data stream was used as input for the analyser. This can be confusing, especially when dealing with screenshots:

![image (7)](https://user-images.githubusercontent.com/4742747/71475951-953fd900-2847-11ea-9ea7-abd85c01fe74.png)

vs.

![image (6)](https://user-images.githubusercontent.com/4742747/71475952-953fd900-2847-11ea-8c4f-c7086a1aa620.png)

A legend should be added to the analyser display to indicate the data stream that the analysis was based on.

**Comment by McGiverGim** [comment]
This has been broken recently. The name must appear at the bottom right of the analyser. This only happens at full screen?

**Comment by mikeller** [comment]
@McGiverGim: You are right, the title is there:

![image](https://user-images.githubusercontent.com/4742747/71492855-5fc6da00-289f-11ea-8995-f15a0e4663c2.png)

It is just very hard to spot behind the green plot - maybe it should go somewhare else like up top centered where it is less likely to be overlaid?

@hydra: Fyi.

**Comment by McGiverGim** [comment]
Usually the noise is almost zero there, so it is more visible. Maybe adding a black border to the letters will make them clearer. I will play a little with it when I have some time.
