### ISSUE TITLE
bug: export video stuck calculating if craft:size or stick:size set to 0%

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/blackbox-log-viewer#425]
Export Video fails to start if the `Craft Settings`:`Size`=`0` or if `Stick Settings`:`Size`=`0`.

Tested v20191223.80
Tested v20191202.76

`Linux 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by McGiverGim** [comment]
I've been looking at this... can be fixed when it fails (when it creates a canvas with size 0) but I think is better to fix it in the settings window 

There are two icons in the main bar that let hide the elements. So it has no sense to have a size 0 for this two elements. So I think we need to limit it to 1% in the settings windows and validate it before saving. Now it admits any value that you put manually (including negatives, etc.).

If someone wants to do it perfect, if not I will do it when I have some time...
