### ISSUE TITLE
bug: pressing H quickly & repeatedly will fade the background completely to black

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/blackbox-log-viewer#427]
Pressing H, waiting for the header display, then pressing H again work fine; however, pressing H quickly multiple times will gradually (or not-so gradually) darken the main interface completely without recovering to normal opacity.

`v20191223.80`

`Linux 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by McGiverGim** [comment]
It seems that this is a bug produced by the `bootstrap.js` library. Is used to show and hide the modal dialogs.

When we press the `H` very fast, the event that "shows/hides" the dialog does not remove the fade div that is in the background, but adds another one in top of it:

![image](https://user-images.githubusercontent.com/2673520/77530792-2bf55380-6e92-11ea-8c11-da00d0742dec.png)

I have tried to update the library without luck, the bug persist, and I'm searching for a workaround for this... someone has experience with this library?

**Comment by mikeller** [comment]
Good find, @McGiverGim!

**Comment by McGiverGim** [comment]
I have found a workaround... I will push a PR in some minutes... let's see if it does not produce other glitches...
