### ISSUE TITLE
Display real values in viewer

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/blackbox-log-viewer#43]
I was wondering why is it not possible to see real value on the right bar instead of percentages?

In my particular case where blackbox is also used for developing / testing I really have to watch the real values often and it is annoying to check the table all the time.

**Comment by GaryKeeble** [comment]
I'll add a user setting toggle so that you can choose raw values / scaled values on the legend ?

**Comment by borisbstyle** [comment]
Yeah that would be nice! Thanks

**Comment by TheAngularity** [comment]
nice feature ... looks good ;-)

**Comment by wolkesson** [comment]
Fixed by 6295f2436a167fc3168f12540dfa4567e8592ee1 by @GaryKeeble . Close this issue!
