### ISSUE TITLE
I see no graphs

### ISSUE THREAD

**Issue by nablabla** [betaflight/blackbox-log-viewer#446]
am i doing it wrong?
every info you need shoud be in the log and the screenshot

**Comment by nablabla** [comment]
[btfl_001.zip](https://github.com/betaflight/blackbox-log-viewer/files/4735230/btfl_001.zip)

**Comment by nablabla** [comment]
![noGraphs](https://user-images.githubusercontent.com/5704918/83862556-685eee80-a722-11ea-86e6-513e38b593e7.png)

**Comment by nablabla** [comment]
> 
> 
> Issue Label Bot is not confident enough to auto-label this issue. See [dashboard](https://mlbot.net/data/betaflight/blackbox-log-viewer) for more details.

what are you talking about, i was not done creating the issue, you have been to fast, sorry

**Comment by spatzengr** [comment]
Looks fine to me.

![image](https://user-images.githubusercontent.com/25570978/83869044-e8bd2980-a6f9-11ea-9e6d-4b429853c90d.png)

Is this a build version of BF BBE or an official release you are using?

**Comment by nablabla** [comment]
code > releases > Blackbox Log Viewer 3.5.0 on windows 10 (i am an expert uc;)

**Comment by nablabla** [comment]
all the guys in tutorial videos just open the file with this application and they hav graphs as you have

**Comment by Asizon** [comment]
O yes, i think it is happens the first time that you open bb explorer after install, just remove current graphs and reads it

**Comment by nablabla** [comment]
i open and closed it several time, problem stays.
"just remove current graphs and re-add it" what is that?

**Comment by Asizon** [comment]
![83862556-685eee80-a722-11ea-86e6-513e38b593e7](https://user-images.githubusercontent.com/43983086/83870445-921e1280-a72e-11ea-8ae1-b86c9c05bf01.png)
Enter in graph setup, remove existing graphs types, and re add

**Comment by nablabla** [comment]
okay, that fixed it. so it is a bug i guess,
thanks for ya help :)

**Comment by spatzengr** [comment]
@nablabla , you can get trace setup Templates from tiny.cc/uavtech --> BBE Trace Templates folder too if you like.  https://www.youtube.com/watch?v=fCs51RQmxqU

**Comment by nablabla** [comment]
> @nablabla , you can get trace setup Templates from tiny.cc/uavtech --> BBE Trace Templates folder too if you like. https://www.youtube.com/watch?v=fCs51RQmxqU
i have watched that already, and i love it, thanks :)
