### ISSUE TITLE
More useful default settings

### ISSUE THREAD

**Issue by 0crap** [betaflight/blackbox-log-viewer#447]
By default the BB log viewer uses Expo ON, Smoothing ON. (Also Grid ON, but I never seen a difference on that setting.)
This gives a unusual/unrealistic view of what happens and is the first thing I always switch off after loading a logfile.
![Default](https://user-images.githubusercontent.com/31951195/84246511-04b03900-ab07-11ea-8866-4e83aff70f4d.jpg)
When setting Expo and Smoothing to OFF it looks much more realistic.
![expo-smooth_off](https://user-images.githubusercontent.com/31951195/84246530-0b3eb080-ab07-11ea-8264-19d95bef3702.jpg)

In a rare case traces are on top of each other and I want to zoom in on what happens, I switch ON Expo.
For better usability and less mouse clicks it would be nice if the defaults can be changed to OFF.
(Maybe remove Grid, never seen that do anyting.)

Your suggestions to discuss this are welcome! :-)

**Comment by ctzsnooze** [comment]
Agree!  It would be great if by default they were off.

**Comment by 0crap** [comment]
@McGiverGim Can you please make the PR? Then we'll see how it goes from there.

**Comment by McGiverGim** [comment]
This weekend I'm out of the computer. If I get some time I will do it next week.

**Comment by mikeller** [comment]
@McGiverGim: No objections from my side. I think the objections were around the fact that the current display mode for this was not visible from screenshots in earlier versions, resulting in misleading screenshots being posted.

**Comment by 0crap** [comment]
@McGiverGim I just installed the latest Configurator nightly build on top of my existing Windows installation. Guess what.... I see now Expo/Smoothing/Grid is automagically switched to Off.

Awesome!
