### ISSUE TITLE
Feature Request : Export to CSV

### ISSUE THREAD

**Issue by goatspoon** [betaflight/blackbox-log-viewer#46]
Previously the .txt files generated by betaflight have been able to be exported to .csv by blackbox-tools. However the new files .bfl have a different format and cannot be interpreted by that tool.

It would be very handy to have a feature where the log can be saved as a CSV for analysis in other software.

**Comment by wolkesson** [comment]
I guess this can be closed with #218 ?

**Comment by McGiverGim** [comment]
True. Closing it 😁
