### ISSUE TITLE
Should there be a graph? It's not showing in 3.5.0

### ISSUE THREAD

**Issue by Nullstr1ng** [betaflight/blackbox-log-viewer#466]
![image](https://user-images.githubusercontent.com/260633/89699967-7ec13a80-d95d-11ea-8ee4-3b222cc937e8.png)

Should there be a graph? It's not showing in 3.5.0.

I am using Windows 10,16GB, 1050Ti, 4GB, SSD 256GB

**Comment by haslinghuis** [comment]
Try https://github.com/betaflight/blackbox-log-viewer/issues/458#issuecomment-670587211
