### ISSUE TITLE
PNR

### ISSUE THREAD

**Issue by HowToMeetLadies** [betaflight/blackbox-log-viewer#468]
1. The app can only be closed using the "Close window" button. Menu and shortcut have no function.
2. - Command+Q
    - "Quit betaflight-blackbox-explorer"
3. MacOs Catalina 10.15.6, Betaflight Blackbox Explorer 3.5.0

**Comment by McGiverGim** [comment]
I mark this as a bug, but I don't have a mac to try to fix it.

**Comment by haslinghuis** [comment]
Latest blackbox explorer is now PWA only so this will no longer be an issue.
