### ISSUE TITLE
Incorrect Scaling of amperageLatest

### ISSUE THREAD

**Issue by goatspoon** [betaflight/blackbox-log-viewer#47]
A multi layer problem. Blackbox-log-viewer displays the value "amperageLatest" which in betaflight is a value in centiamps, it is now a SIGNED int. So a value of 100 corresponds to 1A. Currently 100 is being interpreted as 10A.

Also note that due to changes in betaflight, negative values will be sent in amperageLatest, hopefully those will display correctly.

**Comment by McGiverGim** [comment]
Seems the same problem as https://github.com/betaflight/blackbox-log-viewer/issues/48 and has been fixed.
