### ISSUE TITLE
Loading as unpacked extension in Chrome no longer works properly

### ISSUE THREAD

**Issue by James-T1** [betaflight/blackbox-log-viewer#471]
Loading Blackbox log viewer as an unpacked extension in Chrome per the Readme no longer works properly.  I did a git bisect to find the commit where it broke, and the commit where it quit working was this one: https://github.com/betaflight/blackbox-log-viewer/commit/ec4a79995f3ee91ad8f0ef5c2612d5be942c4c74

Screenshot of working commit previous to that:  
![Working 3 5 0 on commit 91eeea34cc23a8ea6db5a22d0b7b7416ea3819bc](https://user-images.githubusercontent.com/3042407/92930320-84e88200-f407-11ea-9ee0-13f5b4b33226.JPG)

Screenshot of non-working commit:
![Not working 3 5 0 ec4a79995f3ee91ad8f0ef5c2612d5be942c4c74](https://user-images.githubusercontent.com/3042407/92930337-8a45cc80-f407-11ea-8bff-5a895ab1694c.JPG)

Using Google Chrome Version 85.0.4183.83 (Official Build) (64-bit) for Windows 10.

Any ideas on how to get it functional as an unpacked extension again?

**Comment by McGiverGim** [comment]
The theory is that the Chrome extension will get removed soon (Google is removing the support for Chrome apps).

Are you executing a `yarn install` to download the dependencies before loading it as extension?

**Comment by mikeller** [comment]
@McGiverGim: Yeah, my thoughts too - Google will be retiring support for Chrome Web apps soon, so in this case I think the 'fix' is to move forward and remove support for building the Chrome Web app altogether (applies to configurator as well).

**Comment by mikeller** [comment]
Superseded by #474.
