### ISSUE TITLE
Display selected gyro in log header viewer

### ISSUE THREAD

**Issue by bizmar** [betaflight/blackbox-log-viewer#479]
When doing comparisons between logs on FCs that have two gyros it would be useful to have the gyro selected gyro (first, second, both) saved in the log header.

This goes with https://github.com/betaflight/betaflight/issues/10314 requesting saving selected gyro in blackbox logs

**Comment by mikeller** [comment]
Will need a change in the firmware to add this value to the log header in the first place.
