### ISSUE TITLE
"Start Log Here" Log Sync text box does not work when log sync time is manually entered

### ISSUE THREAD

**Issue by joshuabardwell** [betaflight/blackbox-log-viewer#49]
Manually entering the log sync value into the text box does not have any effect. Verified on two PCs. v2.5.9

**Comment by wolkesson** [comment]
This was fixed by commit https://github.com/cleanflight/blackbox-log-viewer/commit/36c045e97a1cf3656f3a0524e9fee82c31a3a520 and later merged into betaflight. Works in 3.0.0. I guess this issue be closed?
