### ISSUE TITLE
Error vs Setpoint zoom/range wierd

### ISSUE THREAD

**Issue by bexamous** [betaflight/blackbox-log-viewer#507]
When viewing Error vs Setpoint, the horizontal zoom/range slider seems wonky.  It might work for a few ticks but then you start seeing some missing bars or no bars, eg:

![BlackboxPIDError-bad](https://user-images.githubusercontent.com/2084920/115349674-fb511d80-a168-11eb-859a-66445e70b405.png)

And while doesn't seem right, one move slider one tick further and suddenly all bars show up again:

![BlackboxPIDError](https://user-images.githubusercontent.com/2084920/115349666-f9875a00-a168-11eb-8b24-575df555826d.png)

It seems there is suffient data, this is a 4 min flight with lots of stick movement.

This is a v3.6.0 nightly from few days ago, but fairly certain its not a recent regression or anything.  I recall this happening last year.

**Comment by McGiverGim** [comment]
This seems some round error at some calculation. Marked as bug.
