### ISSUE TITLE
Question: Possible to recover truncated logs?

### ISSUE THREAD

**Issue by barthalamu** [betaflight/blackbox-log-viewer#51]
Is there a way to repair a BB log file that was truncated due to a crash/battery ejection?
I have a file that looks like it has data, but is blank when loaded into BB viewer.

**Comment by GaryKeeble** [comment]
Can you send the file; maybe I could take a look at it to see why it wont load ?

**Comment by wolkesson** [comment]
This usually works fine for me as long as the header is intact. Any progress with this particular file? Otherwise, I recommend closing this.
