### ISSUE TITLE
Does not show 1080p video only sound and black screen

### ISSUE THREAD

**Issue by tn2009** [betaflight/blackbox-log-viewer#513]
In the blackbox explorer, only 2.7 k, 4k videos are displayed. I add 1080p video at any fps, the video does not appear only sound. I checked on the video from the GoPro Hero 7 Black, Runcam Hybrid.

**Comment by McGiverGim** [comment]
Are you sure all your videos use the same codecs? I've several 1080p videos, from a Runcam Split, and they work perfectly.

We use the ffmpeg library from here: https://github.com/iteufel/nwjs-ffmpeg-prebuilt so we only support the codecs that this library support.

**Comment by tn2009** [comment]
Over the weekend I recorded a lot of videos via Rucam Hybrid. 1080p 60fps no video is displayed (black screen), only audio.

https://disk.yandex.ru/d/IurHH2ldSSbt1Q - information about the video file
