### ISSUE TITLE
Gyro debug lines don't overlap with with other lines of similar values

### ISSUE THREAD

**Issue by akonokhov** [betaflight/blackbox-log-viewer#519]
When I'm putting gyro debug on the same graph with another fields that have the same or similar values, their lines do not overlap but have quite a big distance.
On the attached screenshot, according to the legend, all 5 lines should be somewhere close, at least those that show gyro values (723, 722, 722). But instead non-debug values are shown as expected and there is a distance between them and debug lines (Gyro 1 [roll], Gyro 2 [roll]).
It doesn't seem like a big issue, but it's quite confusing, because when there is a distance between lines, we expect them to have different values.
Blackbox log is attached.
Thanks.

<img width="1435" alt="Screenshot 2021-06-16 at 10 27 44" src="https://user-images.githubusercontent.com/9210645/122189205-64b78900-ce99-11eb-8a3c-5e7336e471ef.png">
<img width="597" alt="Screenshot 2021-06-16 at 10 28 01" src="https://user-images.githubusercontent.com/9210645/122189245-6d0fc400-ce99-11eb-9d9b-ac8344cc31bf.png">

[btfl_001.zip](https://github.com/betaflight/blackbox-log-viewer/files/6661629/btfl_001.zip)

**Comment by akonokhov** [comment]
Forgot to mention that the behaviour is the same in v3.5.0 and in the nightly build (v3.6.0).

**Comment by McGiverGim** [comment]
It seems that the debug mode `DUAL_GYRO_SCALED` that you are using has not been added to the Blackbox. I will add it.

**Comment by McGiverGim** [comment]
@akonokhov you can test the change it if you want here: https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=3056&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by akonokhov** [comment]
@McGiverGim , thanks!
I've tried that link but it doesn't show any artifacts. Also, tried to search Azure pipelines for that build, but didn't find anything.

**Comment by McGiverGim** [comment]
The PR builds only last for some days... If you didn't catch it in time you will need to wait until this is merged or build it yourself.
