### ISSUE TITLE
Empty NW.JS Window

### ISSUE THREAD

**Issue by ClydeFPV** [betaflight/blackbox-log-viewer#534]
Hello Betalflight Devs,

I'm having problems with install of Betaflight Blackbox Explorer and it's now beginning to drive me nuts.  I downloaded the latest version of the Blackbox Log Viewer .exe file from GitHub (betaflight-blackbox-explorer-installer_3.5.0_win32.exe) to my PC (Windows 10 - 64bit). The install seems to run as normal, however when the app is run an empty NW.JS window appears and the app doesn't open (see image below).  The list of the associated app files a directory pathway are also shown below.  I've repeated the install from scratch multiple times over a period of a week and was about to give up when it finally started working late last week. Today however, when I opened the app, the empty NW.JS window is back!  I've searched online for a solution and have posted threads on various RC forums but am now at a complete loss as to what to try next.  Can you help please?  

![blackbox](https://user-images.githubusercontent.com/90517175/134769120-045482b0-583a-46e2-9aa4-734b882874cd.JPG)
![Install Files](https://user-images.githubusercontent.com/90517175/134769122-da2d6fb4-04c1-4161-bab5-91465bb6754a.JPG)

**Comment by haslinghuis** [comment]
Sorry for late reply. Runs fine here. Maybe you could check: https://github.com/betaflight/blackbox-log-viewer-nightlies/releases
