### ISSUE TITLE
Problem spike on roll

### ISSUE THREAD

**Issue by AdrY89** [betaflight/blackbox-log-viewer#537]
Problem spike on roll
Hi friends.
Now with the new version of emuflight i have spike on roll …
So, when I make a rapid roll, sometime I lost the control of drone
I attached some photo of emuflight and bb.
ESC 16.9 48KHZ
Version # EmuFlight / FLYWOOF405 (FWF4) 0.4.0 Aug 23 2021
![bb0](https://user-images.githubusercontent.com/32439602/137593897-07a90d1a-e22c-4f0d-a813-9cf2dbc19d04.png)
![bb1](https://user-images.githubusercontent.com/32439602/137593898-3cd6bcf4-a403-4e56-8744-0fbc818304ee.png)
![bb2](https://user-images.githubusercontent.com/32439602/137593899-61bf16b9-85eb-45c0-bd11-d88713ccd8e5.png)
![emu](https://user-images.githubusercontent.com/32439602/137593900-1fa64086-7187-4fe5-ac10-4bbf5da3a6d1.png)
![emu1](https://user-images.githubusercontent.com/32439602/137593902-398f5ec3-dbc8-48d8-8339-f16b9a8b3aea.png)

**Comment by McGiverGim** [comment]
This is not the support channel for emuflight.
