### ISSUE TITLE
video not visible 

### ISSUE THREAD

**Issue by patkszen** [betaflight/blackbox-log-viewer#538]
1. Audio present but no video is being replayed in blackbox
3. Provide as much information as possible about your hardware and software, including:
 - Win10, Blackbox 
- footage from gorpo6, 2.7K 60fps, no stabilization, mp4

**Comment by haslinghuis** [comment]
Maybe also upload the BBL file so we can test this on our side

**Comment by patkszen** [comment]
I am able to read BBL's. It is when I try to open video with open logfile/video option no video overlay is showing.

**Comment by pcfranco05** [comment]
I am also having the same issue. I can upload some video and a black box log to a google drive if that would be helpful.

**Comment by artem-alexandrov** [comment]
I'm having this one too. Instead of video playing I see black screen. The audio is playing though

**Comment by nerdCopter** [comment]
* maybe the footage is too high resolution. try the gopro LRV lo-res files.
* a workaround maybe, is export video of BBL, and add as a layer over footage in a video-editor.  but then you lose the BBE interaction.

**Comment by artem-alexandrov** [comment]
It may be related that the video I'm trying to play is h265. It's 4k and when converted to h264 it plays just fine

**Comment by artem-alexandrov** [comment]
@haslinghuis hey, it seems like that lib can support HEVC by adding these params when building: `proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true`. I tried default build script with those params added, but the resulting lib file is smaller than the one used in the app (2.9mb vs 3.2mb) and it fails with some error related to audio. Do you build that lib with some different flags? Can you get me a list of params, I'd like to try building it on my end and try playing HEVC files. Thanks

**Comment by haslinghuis** [comment]
@artem-alexandrov no we just drop in the prebuilt version.

As we would do it once manually it would be gone with the next update as we don't like to add additional maintenance.
