### ISSUE TITLE
BF 3.2.0 - max rates not correct reading

### ISSUE THREAD

**Issue by ghost** [betaflight/blackbox-log-viewer#55]
@GaryKeeble 
pls can you see on this issue https://github.com/betaflight/betaflight/issues/2867

**Comment by GaryKeeble** [comment]
@TheAngularity Can you send over your log file to allow me to debug please....

**Comment by TheAngularity** [comment]
@GaryKeeble 
made a new log file ... here it is

[BLACKBOX_LOG_Test_20170413_131222.TXT](https://github.com/betaflight/blackbox-log-viewer/files/919313/BLACKBOX_LOG_Test_20170413_131222.TXT)
