### ISSUE TITLE
Error opening log: No logs in this file could be parsed successfully

### ISSUE THREAD

**Issue by jasonbrewer** [betaflight/blackbox-log-viewer#571]
### Describe the bug

Error opening log: No logs in this file could be parsed successfully

Using a MAC. 
Betaflight blackbox 3.5.0

The file name is : LOG00237.BFL (454kb)
Using Beatflight 10.7.2
Recorded on an SD card onto the FC

### To Reproduce

Open Betaflight blackbox explorer. Click open log. Find log. Open. receive error code Error opening log: No logs in this file could be parsed successfully

### Expected behavior

Open the file

### Betaflight Blackbox Explorer version

3.5.0

**Comment by McGiverGim** [comment]
Without more info, for example the log file with the problem, we can't say too much.
