### ISSUE TITLE
Display BF4.3 log, gyro data not displayed correctly

### ISSUE THREAD

**Issue by jasc76** [betaflight/blackbox-log-viewer#589]
### Describe the bug

I have a build with BF4.3 and the only thing that might be special is, that the fc is flipped upside down. 
Gyro traces (here debug gyro scaled) but also the other gyro stuff is displayed totally wrong. 
I randomly chose BBE 3.4 and it shows the data correctly
[btfl_all.zip](https://github.com/betaflight/blackbox-log-viewer/files/9118133/btfl_all.zip) - Quad without props, armed and moved by hand
BBE3.6.0
![BBe36](https://user-images.githubusercontent.com/42022027/179157997-2f050514-3a22-4580-b456-1fce7f5b7eb3.png)
BBE3.4.0
![BBE34](https://user-images.githubusercontent.com/42022027/179157987-686d16df-6888-4589-8936-5de1c2c02ae1.png)

### To Reproduce

Load attached log file in BBE 3.6 and 3.4

### Expected behavior

Show data correctly

### Betaflight Blackbox Explorer version

3.6.0

### Add any other context about the problem that you think might be relevant here

[btfl_all.zip](https://github.com/betaflight/blackbox-log-viewer/files/9118144/btfl_all.zip)

**Comment by haslinghuis** [comment]
Please post a screenshot of your rates settings as it works fine with defaults settings.

The graph from your log would show up as before using the default case instead:

https://github.com/betaflight/blackbox-log-viewer/blob/25e39c631188ed380f205592e56fd20f438668d1/js/graph_config.js#L192-L208
