### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by nathantsoi** [betaflight/blackbox-log-viewer#61]
after opening and closing a bunch of logs, hitting play and pause, the app freezes:

![screen shot 2017-04-22 at 10 10 20 pm](https://cloud.githubusercontent.com/assets/399770/25311000/e65e2b54-27a8-11e7-9ba1-69fc0da9712f.png)

**Comment by McGiverGim** [comment]
@nathantsoi can you confirm if this is a problem with the latest version too? And easy way to reproduce this?
