### ISSUE TITLE
BBE 3.7.0 Nightly does not decode BaroAlt

### ISSUE THREAD

**Issue by aowi7280** [betaflight/blackbox-log-viewer#611]
### Describe the bug

BB Nightly 3.7.0 (v20221126.30) does not decode the baro altitude in the View Log Header. Released version 3.6.0 works OK.

![BBE Altitude decode](https://user-images.githubusercontent.com/25130267/204195497-c352ddfe-dd1f-48b8-9a33-9bf3cdc81448.JPG)

### To Reproduce

Install 3.7.0, open blackbox log, click the view log header icon on top row.

### Expected behavior

It should decode the altitude from the raw value. And doing it in either feet or meters would be nice.

### Betaflight Blackbox Explorer version

3.7.0

**Comment by haslinghuis** [comment]
@aowi7280 please try with latest firmware as the parameter was renamed.

**Comment by aowi7280** [comment]
It does not seem to work using nightly https://github.com/betaflight/blackbox-log-viewer-nightlies/releases/tag/v20221202.34
