### ISSUE TITLE
Compatibility to INav 1.7 RC1

### ISSUE THREAD

**Issue by DerElch87** [betaflight/blackbox-log-viewer#63]
Hi there,
The viewer shows some problems with the latest INav RC.
The motors are always shown as 100% in the GUI, in the table are still the correct values shown.
The debug values are not pickable or chooseable, necessary for debug mode: gyro/ notch.

Is it possible to get compatibility here again?

BTW
Thanks to all for the great work.

**Comment by mikeller** [comment]
Hi @DerElch87: Maybe you should give this a go: https://github.com/iNavFlight/blackbox-log-viewer
