### ISSUE TITLE
Icon missing in the windows taskbar

### ISSUE THREAD

**Issue by McGiverGim** [betaflight/blackbox-log-viewer#639]
### Describe the bug

The taskbar icon is missing:
![image](https://user-images.githubusercontent.com/2673520/236610446-84c61d93-4a81-47dc-ab10-d63ad8727f43.png)
I don't know why, I've tried to change things/versions without luck. The Configurator icon is right, only the Blackbox one fails.
I'm not too sure if it's only my computer or is a general error.

### To Reproduce

Start the blackbox.

### Expected behavior

To see the correct icon.

### Betaflight Blackbox Explorer version

Latest master

### Add any other context about the problem that you think might be relevant here

There are similar (not the same) errors searching in internet, but for different nw.js version, not ours.

**Comment by haslinghuis** [comment]
This is an NWjs issue. Now we use PWA it's no longer an issue.
