### ISSUE TITLE
BF 3.2 - cannot setup graphs

### ISSUE THREAD

**Issue by playlet** [betaflight/blackbox-log-viewer#68]
Hi!

I'm running the latest BF 3.2 1431.
Blackbox explorer cannot setup graphs for 3.2 logs. Buttons are unresponsive. If I set it up using 3.1.7 log, I can see graphs but that's it. I wanted to see dynamic filter debug info but no dice.

I hope you guys sort this out soon. Thanks

**Comment by McGiverGim** [comment]
Can you try the latest master of cleanflight blackbox explorer? If it works betaflight can cherry pick the changes.

**Comment by playlet** [comment]
Thanks man, CF BB explorer WORKS! I can now analyze my 3.2 logs. Thanks again! :)
