### ISSUE TITLE
Can't open "Freq vs throttle" plots for some logs after #668

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/blackbox-log-viewer#691]
### Describe the bug

Analyzer display doesn't show "Freq vs throttle" data on some logs after #668 
affected fields: gyro, unfiltered_gyro, gyro_scaled maybe other

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/708ea758-6780-4706-9f22-17e130f8ddb1)

[1.txt](https://github.com/betaflight/blackbox-log-viewer/files/14025399/1.txt)

### To Reproduce

- Open provided log file. not sure if it is matter some fields disabled in BF blackbox tab( setpoint and rc commands are on place ).
- Switch to second log in top right menu.
- Add gyro | unfiltered_gyro |  gyro_scaled  and press on any axis. 
- Analyzer display will appear with no data (it is hard to see need to hover the cursor on bottom left area).

f12 console shows error:

`Cannot plot analyser TypeError: Cannot read properties of undefined (reading '0')      grapher.js:878 `

 For first log it works as expected

### Expected behavior

"Analyzer display" shows gyro data.

### Betaflight Blackbox Explorer version

3.7.0 (master)

**Comment by mituritsyn** [comment]
@tbolin could you kindly check it?

**Comment by nerdCopter** [comment]
- using `bfd5ab7e`
- reproducible only on `Freq vs Throttle`, reproducible on a personal Sept 2023 log
