### ISSUE TITLE
Reset analyserZoomX/Y state

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/blackbox-log-viewer#694]
### Describe the bug

Opening new log resets analyserZoomY or analyserZoomX scroll but persist actual plot scale

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/2fcf8f42-88f6-410c-868f-30fef33463bc)
![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/3349252f-08f3-4780-b70d-5adc4fe9915c)

### To Reproduce

- open Analyze plot from any log 
- scale to maximum
- open another file or select next log in multilog file
- notice that analyserZoomY analyserZoomX state reseted to default but plot scale still maxed

### Expected behavior

plot scale corresponds to analyserZoomY state

### Betaflight Blackbox Explorer version

3.7.0 master

**Comment by mituritsyn** [comment]
up

**Comment by nerdCopter** [comment]
resolved by https://github.com/betaflight/blackbox-log-viewer/pull/717
