### ISSUE TITLE
Error while loading the video. ERROR (4): DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams

### ISSUE THREAD

**Issue by elpinguinofrio** [betaflight/blackbox-log-viewer#695]
### Describe the bug

on mac Betaflight Blackbox Explorer 3.6.0 can't open video made made by dji O3 with the error:
Error while loading the video. ERROR (4): DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams

### To Reproduce

record onboard video by dji-03 equipped drone

### Expected behavior

able to render/view video with blackbox data

### Betaflight Blackbox Explorer version

3.6.0

### Add any other context about the problem that you think might be relevant here

laptop: m1 air macOS Monetary 12.4 (21F79), video isn't corrupted i.e. opens in Gyroflow.

**Comment by nerdCopter** [comment]
BBE's included ffmpeg does not include proprietary or non-free codecs.
you will have to convert your video to a free-codec encoded format, usually mp4.
another option is simply export a video of the data traces your desire, and overlay that video over your DVR in a video-editor.
