### ISSUE TITLE
Analyser display overlay not working

### ISSUE THREAD

**Issue by propsinview** [betaflight/blackbox-log-viewer#736]
### Describe the bug

I'm unable to turn on analyser display in the overlay menu. I've imported a log file, but when I click on "View/Hide analyser it, nothing happens. However, I can toggle on/off the craft display and stick display.

### To Reproduce

-

### Expected behavior

-

### Betaflight Blackbox Explorer version

3.6.0

**Comment by haslinghuis** [comment]
Please checkout blackbox.betaflight.com.

**Comment by haslinghuis** [comment]
Please checkout https://blackbox.betaflight.com

**Comment by propsinview** [comment]
Turns out it was a setting - can be closed :)
