### ISSUE TITLE
How to build a NW.js app?

### ISSUE THREAD

**Issue by salem83** [betaflight/blackbox-log-viewer#737]
### Is your feature request related to a problem? Please describe

The app has changed to be a PWA now which needs to be installed beforehand when an internet connection is available.
How can i still build a NW.js app?

### Describe the solution you'd like

Add necessary files to allow NW.js app to be built again.

### Describe alternatives you've considered

The installation as PWA is not possible in an offline environment.

**Comment by GT-Volk** [comment]
I'm interested in the same question. I would be very unpleasantly surprised that the application is now a web application. Please tell me how can I build a local installer like before?

**Comment by McGiverGim** [comment]
I don't think it's possible to have an installer as in the old version, at least for now. 
You can build the PWA app in local using the developing steps, start it and install it from there, but you need all the sources and dependencies first.

**Comment by demvlad** [comment]
This is link to the NW.js version, what is full identity the current nightly PWA version:
https://github.com/nerdCopter/blackbox-log-viewer/tree/20240509_NWjs_plus_Demvlad

**Comment by salem83** [comment]
Great, will check it out! Thanks!

**Comment by demvlad** [comment]
This is link to manual for new nightly version feature:
https://github.com/betaflight/blackbox-log-viewer/pull/726#issuecomment-2079546532

I need non web version too, therefore will try to support this branch sometime.
Anything else, to run PWA local as developers variant is not hardly then self build  previouse NW.js

**Comment by haslinghuis** [comment]
We no longer maintain NWjs builds.

Github is for development.
Discord for support.
