### ISSUE TITLE
A function in blackbox log viewer that allows you to apply different betaflight filter settings to you raw blackbox log data to improve betaflight filter tuning

### ISSUE THREAD

**Issue by Remleyfpv** [betaflight/blackbox-log-viewer#744]
### Is your feature request related to a problem? Please describe

Filter tuning is hard and  takes a lot of time bc you have to go out to the field multiple times

### Describe the solution you'd like

A extra plot in the analyzer window which shows "re-filtered" gyro data based on user input betaflight filter settings. this would IMO improve the betaflight filter tuning process

### Describe alternatives you've considered

Nothing really I tried making a python program which does this but havent gotten far

**Comment by nerdCopter** [comment]
This subject has come up in community for years, but Blackbox explorer gets the least dev activity in the list of the projects to be worked on.
