### ISSUE TITLE
Can't setup graphs when using DFILTER debug_mode (3.1.7)

### ISSUE THREAD

**Issue by sgcdialler** [betaflight/blackbox-log-viewer#76]
I have only tried a couple different debug_modes to see whether or not the problem is specific to DFILTER or not. PIDLOOP and NOTCH debug_mode still allow graph setup in BB viewer as expected. With debug_mode set to DFILTER, graph setup displays as a box with 'Save Changes' and 'Cancel' buttons, and the normal button to add graphs (which doesn't do anything).

I saw a recent issue where BB viewer failed to open BF3.2 logs and tried the suggestion to use Cleanflight's viewer, but neither the most recent Chrome app nor the new Windows-installed version could open the log.

**Comment by McGiverGim** [comment]
If you want to use the Cleanflight version, you must use the latest git version, manually installing it. The chrome or the install version are far old.

**Comment by sgcdialler** [comment]
I tried pulling the latest git version as you suggested and still have issues. I'm attaching the log file I've been using (just change file extension).
[BF-DFILTER.BFL.TXT](https://github.com/betaflight/blackbox-log-viewer/files/1173204/BF-DFILTER.BFL.TXT)

**Comment by McGiverGim** [comment]
Yes, I've tested your log and the DEBUG MODE for DFILTER does not work correctly.

I can modify the Blackbox log, but I need this information:

- What is the unit logged by this DEBUG MODE (Hz maybe?)

I've searched the firmware for this DTERM DEBUG MODE and I can't find nothing. Only the declaration :(

I've modified the blackbox and now it shows info, but I don't know if it is correct.
![image](https://user-images.githubusercontent.com/2673520/28585873-10db04e8-7172-11e7-8766-5c5d76ce8229.png)

**Comment by sgcdialler** [comment]
That would be my guess? I assumed that the DFILTER debug mode was supposed to be for tuning the d-term filter, just like debug NOTCH is for tuning the gyro notch filters.

**Comment by sgcdialler** [comment]
I figured out how to modify the log to open it like you did. It looks to me like it's writing the raw D-term data.

![2017-07-25 14_40_54-betaflight - blackbox explorer](https://user-images.githubusercontent.com/23480194/28588112-6e0bee32-7147-11e7-834c-07ac7d146611.png)

**Comment by McGiverGim** [comment]
I don't know what is the actual state of this, but the DTERM debug mode was removed in latest versions of CF/BF, so maybe is better to close this.
