### ISSUE TITLE
Panning on timeline panel broken when View Table is activated

### ISSUE THREAD

**Issue by X-Stuff** [betaflight/blackbox-log-viewer#792]
### Describe the bug

UI stucks when trying to scroll through log timeline if Table View was activated

### To Reproduce

Chrome
Version 130.0.6723.117 (Official Build) (64-bit)

https://blackbox.betaflight.com/

1. Open any log file

2. Click and hold left mouse button, somewhere on the timeline panel and move mouse left-right (to scroll through timeline):
 <img width="1916" alt="image" src="https://github.com/user-attachments/assets/2d7ba43f-e0a5-41c7-9771-87d849420e9e">

3. Click on View Table
<img width="482" alt="image" src="https://github.com/user-attachments/assets/fa1a516c-263a-464c-8068-22be4e213b05">

 4. Click and hold left mouse button, somewhere on the timeline panel again and try to move mouse left-right:

### Expected behavior

As in 3.6.0 you should be able to hold mouse button and move though timeline

### Betaflight Blackbox Explorer version

3.7.0

**Comment by nerdCopter** [comment]
@demvlad , interested in this?
![image](https://github.com/user-attachments/assets/aab87278-655b-4dc8-bc99-fdb0299b2d23)

**Comment by X-Stuff** [comment]
![image](https://github.com/user-attachments/assets/07b0f54c-13bb-4604-b635-7634eae35acb)

@haslinghuis 
Still reproducible on Deploy Preview:
 
https://github.com/betaflight/blackbox-log-viewer/pull/793#issuecomment-2483349615

**Comment by haslinghuis** [comment]
Can you share the BBL for investigation?

**Comment by X-Stuff** [comment]
Sure!
[LOG00006.zip](https://github.com/user-attachments/files/17805132/LOG00006.zip)

**Comment by haslinghuis** [comment]
Code trips over null values:

![image](https://github.com/user-attachments/assets/0351036f-6675-48d3-abcd-da06481cfeb1)

Second attempt in https://github.com/betaflight/blackbox-log-viewer/pull/794/commits/2efaa6340277cbe4d4305ac45cb393019ebbdfbb
