### ISSUE TITLE
Freq vs Throttle Graph no throttle axis

### ISSUE THREAD

**Issue by PBLaycock** [betaflight/blackbox-log-viewer#798]
### Describe the bug

Freq vs Throttle showing zero precent throttle even though there is throttle data.

There is RC control throttle axis data that is working so not sure if its linking to that graph and or if I am doing something wrong.

### To Reproduce

[btfl_004.bbl.zip](https://github.com/user-attachments/files/17951451/btfl_004.bbl.zip)

Import, use flight 14, display any unfiltered gyro (or any data), freq vs throttle graph.

### Expected behavior

<img width="1708" alt="Screenshot 2024-11-28 at 10 34 16 AM" src="https://github.com/user-attachments/assets/33d23cfb-8011-4b39-962c-0d937cc15ed2">

After importing and doing gyro freq vs throttle graph throttle is displayed as zero

### Betaflight Blackbox Explorer version

3.7, and/or 3.6

**Comment by haslinghuis** [comment]
Did you try https://master.dev.blackbox.betaflight.com

**Comment by PBLaycock** [comment]
> Did you try https://master.dev.blackbox.betaflight.com

I just tried it same result, freq vs rpm always works just freq vs throttle

**Comment by demvlad** [comment]
> ### Describe the bug
> Freq vs Throttle showing zero precent throttle even though there is throttle data.
@PBLaycock 
You should enable log 'setpoint' data, to get spectrum by throttle. The spectrum by throttle uses throttle setpoint value, it is not throttle RC value.

**Comment by PBLaycock** [comment]
Okay thank you, on me no real issue.
