### ISSUE TITLE
Right Stick Overlay not Displaying correctly (position of stick)

### ISSUE THREAD

**Issue by Ozzy33** [betaflight/blackbox-log-viewer#80]
I notice the right stick overlay is not showing the stick in the corner (my roll and pitch rates are 1950d/s), but the stick is shown quite a bit aways from the corner.
Picture in my rcg post here
[https://www.rcgroups.com/forums/showpost.php?p=38102177&postcount=201](url)

**Comment by wolkesson** [comment]
I guess this is already solved by #164?

**Comment by McGiverGim** [comment]
I think that yes.

**Comment by McGiverGim** [comment]
I close this issue, because it seems to be fixed. If not it can be opened again.
