### ISSUE TITLE
No response from controller

### ISSUE THREAD

**Issue by mathia53** [betaflight/blackbox-log-viewer#85]
I use the sp racing flight controller on my racing drone, and I have got the issue that the blackbox viewer does not show my stick movements. I have got a connection between my reciever and transmitter, but neighter the drone or blackbox log viewer will give any response from my transmitter when i arm/throttle up/navigate. I have invested a lot of money and time into this project, and I'm getting desperate since it havent shown any sign og flying yet...

**Comment by mikeller** [comment]
@mathia53: GitHub is for discussion and questions around the development of Betaflight. For questions about the configuration and use of Betaflight, please see [RCGroups](https://www.rcgroups.com/forums/search.php?searchid=62448257&query=betaflight%20connect%20configurator).

Also, for configuring your craft, you want to use the Betaflight configurator, and not the blackbox log viewer.
