### ISSUE TITLE
Q: Any plans for a Standalone App?

### ISSUE THREAD

**Issue by richard-scott** [betaflight/blackbox-log-viewer#96]
With the demise of Chrome Extensions, what plans does this project have to migrate over to a Standalone App?

**Comment by mikeller** [comment]
Already done: #88.

**Comment by richard-scott** [comment]
Great, where can I download it from?

**Comment by richard-scott** [comment]
I've tried building from source with the same gulp commands I use for Betaflight Configurator or BLHeli and I do not get the expected executable created. No errors, just no App.

**Comment by mikeller** [comment]
https://github.com/betaflight/blackbox-log-viewer . You'll have to build it yourself for now, we have not yet done a release.

I think there might be a problem with how gulp is handling concurrent tasks in our build processes. We're currently looking into this in the betaflight-configurator (betaflight/betaflight-configurator#830). Once this is sorted, we'll apply the learnings here.

**Comment by richard-scott** [comment]
ok, thanks for the info.

**Comment by basdelfos** [comment]
Yes, I was planning to do the same fix here when betaflight/betaflight-configurator#830 is ironed out (same for BLHeli configurator)
